"""The range briefing: a human-readable summary of a defense range.

Terraform outputs give the addresses and the generated credentials; the canvas
document gives what infrastructure never knows - the domains, the users and
their planted flaws, the trusts, the ACL attack paths. This joins the two into
one hand-off an operator reads after a deploy: every box and its role, every
account and credential, every lab user with their privilege and flaws, the
domains and trusts, the planted vulnerabilities, and the SIEM dashboards.

The addresses are `<<tf:name:field>>` placeholders that tools/tf_inventory.py
fills in after `terraform apply`, the same tokens the Ansible tree uses. The one
credential not embedded is the generated lab password, which lives only in the
Terraform state; the briefing points at `terraform output -raw lab_password`.
See goad-native-recreation.
"""

from .naming import platform_account
from .validate import Context

PLACEHOLDER = "<<tf:%s:%s>>"

_KIND_ROLE = {
    "dc": "Domain Controller",
    "srv": "Server",
    "wks": "Workstation",
    "siem": "SIEM",
    "jumpbox": "Jumpbox",
}

# The fallback the dc role sprays onto an account carrying the `weak_password`
# flaw that declares NO password of its own (attack_paths.yml). It is the only
# case that produces a password the document does not already state, and it is
# rare: nearly every flagged GOAD account declares its own credential.
_WEAK_PASSWORD = "Summer2024!"


def _briefing_password(user):
    """The credential the dc role actually seeds for a user, stated the same way
    the role decides it (dc/tasks/main.yml + attack_paths.yml), so the briefing
    matches the deployed range rather than guessing from flaws.

    1. A declared `password` is the lab's documented credential and wins outright
       -- the role enforces it every run, and the weak-password step explicitly
       skips any account that declares one. These are already public in the
       shipped vars/domains/*.yml, so naming them here reveals nothing new and
       makes the briefing a usable hand-off.
    2. Otherwise, an account flagged `weak_password` gets its `weak_password`
       value or the Summer2024! fallback -- exactly the role's condition.
    3. Otherwise the account has the shared lab password.
    """
    declared = user.get("password")
    if declared:
        return "`%s`" % declared
    if "weak_password" in (user.get("flaws") or []):
        return "`%s`" % (user.get("weak_password") or _WEAK_PASSWORD)
    return "lab password"


def _tok(ctx, node_id, field):
    return PLACEHOLDER % (ctx.name(node_id), field)


def _domain_of(ctx, host_id):
    for e in ctx.by_role.get("joins", []):
        if e["source"] == host_id and ctx.kind(e["target"]) == "domain":
            return e["target"]
    return None


def _dc_of(ctx, domain_id):
    for e in ctx.by_role.get("joins", []):
        if e["target"] == domain_id and ctx.kind(e["source"]) == "dc":
            return e["source"]
    return None


def range_briefing(document, registry=None):
    ctx = Context(document, registry)
    account = platform_account(document.get("mode"))
    # Assumed-breach foothold users (P2.5): patient zero, a jumpbox local admin
    # and a low-priv domain member at once. See range-access-model.
    breach = [(u["username"], (d.get("overlay") or {}).get("fqdn"))
              for d in ctx.of_kind("domain")
              for u in ((d.get("overlay") or {}).get("users") or [])
              if u.get("assumed_breach")]
    name = document.get("name") or "redStackPRO range"
    lines = [
        "# %s - Range Briefing" % name,
        "",
        "Generated by redStackPRO. Addresses fill in after `terraform apply`,",
        "when `tools/tf_inventory.py` resolves the address placeholders.",
        "The shared lab password is generated at apply and lives only in your",
        "state: read it with `terraform output -raw lab_password`.",
    ]

    jumps = ctx.of_kind("jumpbox")
    jump = jumps[0] if jumps else None

    # -- The access model (external red-team POV), stated up front so the range
    # reads the same on every provider. See range-access-model / P0.2.
    if jump:
        lines += [
            "", "## The access model", "",
            "This range is built for an **external red-team POV**. The jumpbox is "
            "the only host with a public address and your single initial-access "
            "foothold; every other host is private (no public IP) and reachable "
            "only from the jumpbox or from inside the range subnet.",
            "",
            "- **Get in** at the Guacamole portal. That is the way in for this "
            "range: every host is a tile, Windows over RDP and Linux over SSH, "
            "and each one opens on a click. Jumpbox SSH stays available for "
            "scripting and `ProxyJump`, but the portal is the intended path.",
            "- **No direct path** from your machine to a backend host: management "
            "and attack traffic both route through the jumpbox, and there is no "
            "peering into the range.",
            "- **C2 rides outbound** (HTTPS or DNS) from a compromised host to the "
            "redirector; nothing calls back into the range.",
        ]
        if breach:
            lines.append(
                "- **Patient zero** is the assumed-breach foothold under Access "
                "below: a low-priv domain member you already hold. Open its RDP "
                "tile in the portal to work as that user, drop your beacon onto "
                "the mapped `redstackpro` drive, and run it there -- the beacon "
                "then lives in patient zero's context, which is where the "
                "engagement starts.")

    # -- Access
    lines += ["", "## Access", ""]
    if jump:
        addr = _tok(ctx, jump["id"], "public_address")
        lines += [
            "- **Guacamole portal:** https://%s/guacamole" % addr,
            "- **Portal login:** `operator` / the lab password "
            "(`terraform output -raw lab_password`)",
            "- **Jumpbox SSH:** `ssh %s@%s`" % (account, addr),
            "- Every box is reachable from the portal (Windows over RDP, Linux "
            "over SSH) and from any host on the range subnet.",
        ]
        for user, dom in breach:
            lines.append(
                "- **Assumed-breach foothold:** patient zero is `%s`, a low-priv "
                "`%s` domain member. Its portal tile logs straight in as that "
                "user with the lab password. The same name is also a local admin "
                "on the jumpbox, but jumpbox SSH is key-only, so that password "
                "opens the domain identity, not a shell here." % (user, dom))
    else:
        lines.append("- No jumpbox in this range.")

    # -- Shared credentials
    lines += [
        "", "## Credentials", "",
        "One shared **lab password** covers `%s` (SSH admin), the `operator`" % account,
        "account (RDP / portal), the built-in / domain **Administrator** on every",
        "Windows box, and every lab user below unless a flaw makes it weak.",
        "Get it with `terraform output -raw lab_password`.",
    ]

    # -- Hosts
    hosts = sorted(ctx.hosts(), key=lambda n: (n["kind"], n["id"]))
    lines += ["", "## Hosts (%d)" % len(hosts), "",
              "| Host | Role | OS | Domain | Address | EDR |",
              "| --- | --- | --- | --- | --- | --- |"]
    for h in hosts:
        ov = h.get("overlay", {})
        role = _KIND_ROLE.get(h["kind"], h["kind"])
        if h["kind"] == "siem" and ov.get("product"):
            role = "SIEM (%s)" % ov["product"]
        elif ov.get("role") and ov["role"] != "generic":
            role = "%s (%s)" % (role, ov["role"])
        services = ov.get("services") or []
        if services:
            role = "%s [%s]" % (role, ", ".join(services))
        dom_id = _domain_of(ctx, h["id"])
        domain = ctx.overlay(dom_id, "fqdn", "-") if dom_id else "-"
        field = "public_address" if h["kind"] == "jumpbox" else "private_address"
        addr = _tok(ctx, h["id"], field)
        hostname = ov.get("hostname", h["id"])
        lines.append("| %s | %s | %s | %s | %s | %s |" % (
            hostname, role, ov.get("os", "-"), domain, addr,
            ov.get("edr", "-")))

    # -- Domains and trusts
    domains = ctx.of_kind("domain")
    if domains:
        lines += ["", "## Domains & trusts", ""]
        trusts = ctx.by_role.get("trusts", [])
        for d in sorted(domains, key=lambda n: ctx.overlay(n["id"], "fqdn", "")):
            fqdn = ctx.overlay(d["id"], "fqdn", d["id"])
            netbios = ctx.overlay(d["id"], "netbios", "")
            dc = _dc_of(ctx, d["id"])
            dc_name = ctx.overlay(dc, "hostname", dc) if dc else "-"
            lines.append("- **%s**%s - DC `%s`" % (
                fqdn, (" (%s)" % netbios) if netbios else "", dc_name))
            for t in trusts:
                if t["source"] == d["id"]:
                    tgt = ctx.overlay(t["target"], "fqdn", t["target"])
                    lines.append("    - trusts **%s** (%s%s)" % (
                        tgt, t.get("trust_type", "trust"),
                        ", transitive" if t.get("transitive") else ""))

    # -- Domain users
    user_domains = [d for d in domains if ctx.overlay(d["id"], "users")]
    if user_domains:
        lines += ["", "## Domain users", ""]
        for d in sorted(user_domains,
                        key=lambda n: ctx.overlay(n["id"], "fqdn", "")):
            fqdn = ctx.overlay(d["id"], "fqdn", d["id"])
            users = ctx.overlay(d["id"], "users") or []
            lines += ["", "### %s (%d users)" % (fqdn, len(users)), "",
                      "| User | Name | Privilege | Groups | Flaws | Password |",
                      "| --- | --- | --- | --- | --- | --- |"]
            for u in users:
                flaws = u.get("flaws") or []
                pw = _briefing_password(u)
                lines.append("| %s | %s | %s | %s | %s | %s |" % (
                    u.get("username", "-"),
                    u.get("display_name", u.get("username", "-")),
                    u.get("privilege", "user"),
                    ", ".join(u.get("groups") or []) or "-",
                    ", ".join(flaws) or "-",
                    pw))

    # -- Attack surface
    host_vulns = [(h, h.get("overlay", {}).get("vulns") or [])
                  for h in hosts]
    host_vulns = [(h, v) for h, v in host_vulns if v]
    acl_domains = [d for d in domains if ctx.overlay(d["id"], "acls")]
    if host_vulns or acl_domains:
        lines += ["", "## Planted attack surface", ""]
        for h, v in host_vulns:
            hostname = h.get("overlay", {}).get("hostname", h["id"])
            lines.append("- **%s** host vulns: %s" % (hostname, ", ".join(v)))
        for d in acl_domains:
            fqdn = ctx.overlay(d["id"], "fqdn", d["id"])
            acls = ctx.overlay(d["id"], "acls") or []
            lines.append("- **%s** ACL chains (%d): %s" % (
                fqdn, len(acls),
                "; ".join("%s -%s-> %s" % (
                    a.get("principal", "?"), a.get("right", "?"),
                    a.get("target", "?")) for a in acls[:12])
                + (" ..." if len(acls) > 12 else "")))

    # -- SIEM
    siems = ctx.of_kind("siem")
    if siems:
        lines += ["", "## SIEM dashboards", ""]
        for s in siems:
            product = ctx.overlay(s["id"], "product", "")
            addr = _tok(ctx, s["id"], "private_address")
            if product in ("elk", "elasticsearch"):
                lines.append("- **Kibana (ELK):** http://%s:5601 (open, no login)"
                             % addr)
            elif product == "wazuh":
                lines.append("- **Wazuh dashboard:** https://%s - login `admin` "
                             "(the lab password with any symbol outside `.*+?-` "
                             "replaced by `-`, per Wazuh's charset rule)" % addr)
            else:
                lines.append("- **%s:** %s" % (product or "SIEM", addr))
        lines.append("- Every Windows host ships to each SIEM the range has "
                     "(Winlogbeat to ELK, the Wazuh agent to Wazuh).")

    return "\n".join(lines) + "\n"
