"""Export assembly.

A compile produces the complete working directory: generated code plus the
static modules and roles. Both halves live here so the API and the CLI cannot
produce different output. See 0010 and 0015.

Static assets ship inside the package because the API needs them at runtime.
They are still ordinary version controlled files, reviewable and editable, just
under src/redstackpro/assets/ rather than at the repo root.
"""

from pathlib import Path

from .ansible import generate as generate_ansible
from .deploy import generate_deploy_script
from .naming import platform_account
from .registry import Registry
from .terraform import GenerationError
from .terraform import generate as generate_terraform

ASSETS = Path(__file__).resolve().parent / "assets"

# What has to be filled in before apply, per provider. The variables differ
# because the providers do: GCP scopes everything to a project and AWS does not.
TFVARS_TO_FILL = {
    "gcp": "project, ssh_public_key, operator_source_ranges",
    "aws": "ssh_public_key, operator_source_ranges, region",
}

# Things the account has to have done before apply, which an export cannot do
# for you because redStackPRO touches no account. See 0001.
ACCOUNT_PRECONDITIONS = {
    "aws": """
## Before apply

The Kali image is a Marketplace listing, so the account needs a one time
subscription to it before an operator box with `os: kali` will launch. Without
it `terraform apply` stops with `OptInRequired`. redStackPRO generates code and
touches no account, so this is yours to do once.

Every subnet lands in one availability zone. It defaults to the first in the
region, and `availability_zone` in terraform.tfvars overrides it.
""",
}

# How to authenticate, per provider. Kept beside the tfvars list because they are
# the same kind of fact: the one thing an export cannot do for you.
CLOUD_AUTH = {
    "gcp": """```bash
gcloud auth login
gcloud auth application-default login
```

Run both. Terraform reads only the second, and only the first is obvious when it
lapses, which is how a deploy fails here with everything else set up correctly.""",
    "aws": """```bash
aws configure
aws sts get-caller-identity   # should name your account
```""",
    "azure": """```bash
az login
```""",
}

# Making the key is the OTHER place the platforms differ, and it is the one that
# bites hardest because nothing complains at the time. PowerShell passes `-N ""`
# through as two literal quote characters, so the key gets a passphrase of `""`
# and the deploy fails minutes later with `Permission denied (publickey)` from
# the jumpbox. `-N ''` is the form that yields no passphrase there. Found by
# following the bash version of this line at a PowerShell prompt.
MAKE_A_KEY = """**macOS, Linux, or Git Bash on Windows:**

```bash
ssh-keygen -t ed25519 -f keys/id_ed25519 -N ""
```

**Windows PowerShell** -- the quoting differs, and getting it wrong does not
fail until much later:

```powershell
ssh-keygen -t ed25519 -f keys\\id_ed25519 -N ''
```

`keys/` is beside this file and is where the deploy looks. Already have a key?
Point at it instead with `REDSTACKPRO_SSH_KEY=/path/to/key`.

Get this right before the first apply. The public key is written into each host's
metadata at creation and Terraform ignores later changes to it, so changing it
afterwards means destroying and re-applying. `keys/README.md` has the detail."""

# The deploy step is the one place the two platforms genuinely differ, so it is
# the one place the instructions split. Everything above and below it is shared.
# deploy.ps1 is a wrapper around the same deploy.sh, not a second implementation.
RUN_THE_DEPLOY = """**Windows** (PowerShell, from this folder):

```powershell
.\\deploy.ps1
```

**macOS and Linux**:

```bash
bash deploy.sh
```

On Windows, do not run `bash deploy.sh` at a PowerShell prompt. `bash` there is
`C:\\Windows\\System32\\bash.exe`, the WSL launcher, so the deploy would run in a
different filesystem with a different home and different cloud credentials.
`deploy.ps1` finds Git Bash and calls it properly. From Git Bash itself,
`bash deploy.sh` is correct."""

README = """# {name}

Attack infrastructure for **{provider}**, generated by redStackPRO. Nothing here
has been applied and nothing here holds a credential.

## What you need

| | |
|---|---|
| On your machine | `terraform`, `ssh`, `tar`, and a Python 3.8+ |
| On the hosts | nothing: Ansible is installed on the jumpbox for you |
| Time | roughly 60 to 75 minutes, most of it building C2 agents |

All four local tools ship with Git for Windows, macOS and any Linux, so this
deploys the same way on all three.

## 1. Make an ssh key

{make_a_key}

## 2. Fill in `terraform/terraform.tfvars`

Set: **{tfvars}**

`ssh_public_key` is the single line in `keys/id_ed25519.pub`. The two halves have
to match: Terraform puts the public half on every host and the deploy
authenticates with the private half.

## 3. Authenticate to your cloud

{cloud_auth}
{preconditions}
## 4. Run the deploy

{run_the_deploy}

## What happens then

`deploy.sh` is the whole deploy. It applies the Terraform, fills the address
placeholders from `terraform output`, stages the Ansible tree onto the jumpbox,
and provisions **from the jumpbox** -- the other hosts sit on a private subnet
only it can reach, so the playbook cannot be driven from your machine.

It refuses early, with a reason, if a tool is missing, if your cloud credentials
are not set, or if the build's own auto-stop would fire before it finished.

Provisioning runs in a detached `screen` and keeps going if you disconnect:

```bash
ssh {jumpuser}@<jumpbox> 'tail -f ~/provision/run.log'
```

`RUN EXITED ok=1` means it is done. Then open the portal at
`https://<jumpbox>/guacamole`, with
`terraform -chdir=terraform output guacamole` for the credentials.

If a redirector uses Let's Encrypt, `deploy.sh` prints the exact DNS A record to
create the moment the address exists. Create it while the build runs: issuance
waits about 15 minutes, then carries on with a self-signed certificate that
`sudo rsp-issue-cert` can replace later without redeploying.

## Notes that save an hour

A large topology can exceed the default GCP per-project vCPU quota
(`CPUS_ALL_REGIONS`); raise it before deploying.

A Windows operator box is reached over `psrp` on 5986, not ssh, so it has no
ProxyJump. Put the control node on the jumpbox VPN, or set `ansible_psrp_proxy`
to a SOCKS proxy through the jumpbox, before running the operators play.

The jumpbox builds a certificate authority first and everything else validates
against it, which is why its play runs before the rest. Play order comes from the
topology, so this happens on its own.

A Windows box boots with a self-signed WinRM listener so that it is reachable at
all; an early play signs that listener from the jumpbox authority and rebinds it.
That first connection is the one place validation is off, it needs no flag from
you, and a re-run that finds the listener already signed does not repeat it.

## What redStackPRO did not do

It did not run Terraform, hold a credential, or reach any environment. It
generated files. Everything above happens on your machine under your credentials.

No credentials, no key material and no tfvars values are in this export. The
certificate authority key, the portal password and any HEC token are generated on
your hosts at run time and never leave them.

Terraform and Ansible are not bundled. Install your own.
"""


RANGE_README = """# {name}

A defensive range for **{provider}**: an Active Directory forest recreated
natively from the canvas, not imported or wrapped. Generated by redStackPRO.
Nothing here has been applied and nothing here holds a credential.

**Read `RANGE-BRIEFING.md` next.** It lists every host, account, lab user, trust
and planted weakness in this specific range. It is the source of truth for what
you are attacking; this file is only how to stand it up.

## What you need

| | |
|---|---|
| On your machine | `terraform`, `ssh`, `tar`, and a Python 3.8+ |
| On the hosts | nothing: Ansible is installed on the jumpbox for you |
| Time | roughly 45 minutes for a small forest, longer for a large one |

All four local tools ship with Git for Windows, macOS and any Linux, so this
deploys the same way on all three.

## 1. Make an ssh key

{make_a_key}

## 2. Fill in `terraform/terraform.tfvars`

Set: **{tfvars}**

`ssh_public_key` is the single line in `keys/id_ed25519.pub`. The two halves have
to match: Terraform puts the public half on every host and the deploy
authenticates with the private half.

## 3. Authenticate to your cloud

{cloud_auth}

## 4. Run the deploy

{run_the_deploy}

## What happens then

`deploy.sh` is the whole deploy. It applies the Terraform, captures the shared
lab password from `terraform output` (it is never written into this export),
fills the address placeholders, stages the Ansible tree onto the jumpbox, and
builds the directory **from the jumpbox** -- the controllers and members sit on a
private lab subnet only it can reach.

Standing up a forest is slower than it looks and that is expected: the deploy
waits for each fresh Windows host to answer an *authenticated* WinRM ping before
promoting it, and retries to ride the WinRM flap a freshly promoted domain
controller shows. An attempt that fails and is retried is normal, not a fault.

Provisioning runs in a detached `screen` and keeps going if you disconnect:

```bash
ssh {jumpuser}@<jumpbox> 'tail -f ~/provision/run.log'
```

`RUN EXITED ok=1` means it is done. Then open the portal at
`https://<jumpbox>/guacamole`, with
`terraform -chdir=terraform output guacamole` for the credentials. The portal is
the way in: it has a tile for each host, including one that logs you in as the
range's assumed-breach user.

## What this builds

redStackPRO's own Terraform stands up the hosts and its own Ansible builds the
directory: the forest root and any child domains, the trusts between them, the
domain controllers, and the member servers and workstations that join them, with
the users and groups the canvas defined. There is no GOAD toolchain and no
`goad.py`. GOAD is the inspiration and the fidelity benchmark; this lab is
recreated natively from the range you drew.

## Reaching the hosts yourself

The Windows hosts are provisioned over WinRM (psrp) as the local Administrator,
whose password is the shared lab password above. A range is an isolated subnet,
so the listener is self-signed and the control node does not validate it.

A Linux member or SIEM box is reached over ssh through the jumpbox with a
ProxyJump. ssh does not pass your `-i` key to the jump host, so add it to an
agent first or the jump falls back to a password and fails:

```bash
ssh-add keys/id_ed25519
```

Working from the jumpbox itself avoids the proxy and the agent entirely.

## What redStackPRO did not do

It did not run Terraform, hold a credential, or reach any environment. It
generated files. Everything above happens on your machine under your credentials.
Terraform and Ansible are not bundled. Install your own.
"""


def _read_tree(root, prefix):
    """Static files, keyed by their path in the export."""
    files = {}
    for path in sorted(root.rglob("*")):
        if not path.is_file() or "__pycache__" in path.parts:
            continue
        files["%s/%s" % (prefix, path.relative_to(root).as_posix())] = \
            path.read_text(encoding="utf-8")
    return files


def static_files(provider="gcp"):
    """Modules for the target provider only, plus the whole role library.

    Shipping three providers' modules in one export would leave two thirds of
    the tree unreferenced, and `terraform init` reads every directory it can
    reach.
    """
    files = {}

    modules = ASSETS / "terraform/modules" / provider
    if not modules.is_dir():
        raise FileNotFoundError(
            "no static modules for provider %r; expected %s" % (provider, modules))
    files.update(_read_tree(modules, "terraform/modules/%s" % provider))

    # Provider-agnostic boot scripts referenced by the generated terraform via
    # file() -- the offense Windows operator's setup, delivered as a metadata key
    # and run once at boot. Shipped for every provider so the file() resolves.
    files.update(_read_tree(ASSETS / "terraform/scripts", "terraform/scripts"))

    files.update(_read_tree(ASSETS / "ansible/roles", "ansible/roles"))
    files["ansible/requirements.yml"] = (
        ASSETS / "ansible/requirements.yml").read_text(encoding="utf-8")
    files["ansible/.ansible-lint"] = (
        ASSETS / "ansible/.ansible-lint").read_text(encoding="utf-8")
    files["ansible.cfg"] = (ASSETS / "ansible.cfg").read_text(encoding="utf-8")

    tool = ASSETS / "tf_inventory.py"
    if tool.is_file():
        files["tf_inventory.py"] = tool.read_text(encoding="utf-8")
    return files


# Every native backend knows the Windows host kinds, which in the registry is the
# `windows_image` capability. Module scope rather than a local, because the canvas
# offers the same set and test_range_providers_sync pins the two together -- this
# list and the toolbar's used to disagree, and esxi was the casualty.
RANGE_PROVIDERS = ("aws", "gcp", "proxmox", "azure", "esxi")


def compile_topology(document, registry=None, provider="gcp", region=None):
    """The whole working directory as {path: contents}.

    This is the artifact 0010 makes primary. The archive endpoint and the CLI
    are both formatters over it. Both an offense range and a defense range
    compile to a redStackPRO terraform + ansible working directory through the
    same native pipeline: a defense range is an Active Directory forest recreated
    natively on the canvas, not a GOAD package. GOAD is the inspiration and the
    fidelity benchmark; redStackPRO is the engine. See goad-native-recreation.
    """
    is_range = (document or {}).get("mode") == "range"

    if is_range and provider not in RANGE_PROVIDERS:
        # Rather than emit a broken tree for a provider without one, say so.
        raise GenerationError(
            "a native defense range targets %s; %r is not a native range "
            "provider." % (", ".join(RANGE_PROVIDERS), provider))

    registry = registry or Registry()
    files = {}
    files.update(generate_terraform(document, registry, provider=provider,
                                    region=region))
    files.update(generate_ansible(document, registry, provider=provider))
    files.update(static_files(provider))
    # The one-command deploy: apply Terraform, then provision from the jumpbox
    # (the managed hosts are on a private subnet only it can reach). Emitted only
    # when the topology has a jumpbox to stage through. Provider-aware: a GCP export
    # gets the cloud-auth and Kali-image preflight. See deploy.py.
    deploy = generate_deploy_script(document, registry, provider=provider)
    if deploy:
        files["deploy.sh"] = deploy
        # The Windows front door, and the folder the operator's own key goes in.
        # Both ship with the deploy or not at all: they are only meaningful when
        # there is a jumpbox to deploy through. See deploy.py for why the wrapper
        # has to exist at all (`bash` at a PowerShell prompt is the WSL launcher).
        from .deploy import DEPLOY_PS1, KEYS_README
        files["deploy.ps1"] = DEPLOY_PS1
        files["keys/README.md"] = KEYS_README
    files["README.md"] = (RANGE_README if is_range else README).format(
        name=document.get("name", "redStackPRO export"),
        provider=provider,
        jumpuser=platform_account((document or {}).get("mode")),
        tfvars=TFVARS_TO_FILL.get(provider, "see variables.tf"),
        cloud_auth=CLOUD_AUTH.get(
            provider, "However your provider expects. redStackPRO never holds "
                      "a credential."),
        make_a_key=MAKE_A_KEY,
        run_the_deploy=RUN_THE_DEPLOY,
        preconditions="" if is_range else ACCOUNT_PRECONDITIONS.get(provider, ""))
    if is_range:
        # The hand-off summary: every box, account, lab user, trust, attack path,
        # and SIEM dashboard, joined from the document and the terraform address
        # tokens. tf_inventory fills the addresses after apply. See briefing.py.
        from .briefing import range_briefing
        files["RANGE-BRIEFING.md"] = range_briefing(document, registry)

    # Every file ships with LF line endings, uniformly across all providers and
    # both modes. This is the single choke point every export passes through, so
    # a static asset that was checked out with CRLF (or any future emitter) can
    # never leave a stray \r -- which on the operator's box would break a shell
    # script's shebang (`env: bash\r`) or a heredoc. The whole tree is text.
    return {path: _lf(contents) for path, contents in files.items()}


def _lf(text):
    """Normalize to LF."""
    return text.replace("\r\n", "\n").replace("\r", "\n")
