#!/usr/bin/env python3
"""Generate a per-lab solution set from the authored GOAD series.

The GOAD series in docs/solutions/goad/ is written against the **goad** lab, the
largest one. The smaller labs are strict subsets of it, so a reader who deployed
goad-light was previously handed pages full of hosts and forests that do not
exist on their range, with the bad news arriving only in a footnote at the end of
the section they had just read.

Rather than maintain a second hand-written copy per lab, which would drift, the
per-lab sets are generated: the lab's own canvas template already declares its
attack surface, so it can say which parts and which steps apply to it.

A lab's surface has two dimensions, and counting either alone is misleading (see
docs/solutions/labs/README.md):

    host vulns   overlay.vulns on a host node            esc1, iis_webshell, ...
    user flaws   overlay.users[].flaws on a domain node  kerberoastable, ...
                 plus the presence of spns and delegate_to

Authored pages opt in to filtering with an HTML comment, which renders as
nothing on GitHub:

    ## Step 5 - Trusted links (cross-forest)
    <!-- lab-requires: mssql_linked -->

A section whose requirement the lab cannot meet is dropped from that lab's copy
and listed in a footer, so it is visible that something was removed and why. An
**unmarked section is always kept**: annotation is opt-in, so a missing marker
shows a reader too much rather than silently deleting a step from their guide.
A marker naming several techniques is satisfied if the lab has any of them.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

# tools now lives at src/redstackpro/tools/; the repo root is three parents up
# (tools -> redstackpro -> src -> repo root). docs/ and frontend/ stay at the root.
ROOT = Path(__file__).resolve().parents[3]
SOURCE_DIR = ROOT / "docs" / "solutions" / "goad"
TEMPLATE_DIR = ROOT / "frontend" / "public" / "goad"
SOLUTIONS_DIR = ROOT / "docs" / "solutions"

# Only labs the coverage matrix calls a strict subset of goad are generated.
# goad-wazuh, nha and minilab each carry techniques the goad series never
# exercises, so a filtered copy of that series would be an incomplete guide to
# them rather than a smaller one. They keep their hand-written coverage page.
GENERATED_LABS = ("goad-light", "goad-mini")

MARKER = re.compile(r"<!--\s*lab-requires:\s*(.+?)\s*-->", re.IGNORECASE)
ONLY = re.compile(r"<!--\s*lab-only:\s*(.+?)\s*-->", re.IGNORECASE)
HEADING = re.compile(r"^##\s+(.*)$")
PART_FILE = re.compile(r"^part-\d+-.*\.md$")
PART_LINK = re.compile(r"\]\((part-\d+-[a-z0-9-]+\.md)(#[^)]*)?\)")

BANNER = """> **Generated for the `{lab}` lab.** Do not edit this file; edit
> [the source page]({source}) and run `python -m redstackpro.tools.gen_solutions`.
> {dropped_note}
"""


def lab_surface(template: dict) -> set[str]:
    """Every technique id the lab actually carries, across both dimensions."""
    surface: set[str] = set()
    for node in template.get("nodes", []):
        overlay = node.get("overlay") or {}
        surface.update(overlay.get("vulns") or [])
        for user in overlay.get("users") or []:
            surface.update(user.get("flaws") or [])
            if user.get("spns"):
                surface.add("spns")
            if user.get("delegate_to"):
                surface.add("delegate_to")
    return surface


OPEN_PRINCIPALS = ("anonymous logon", "everyone", "authenticated users", "pre-windows 2000")


def _is_open_principal(principal: str | None) -> bool:
    """True for a grant to everyone rather than to a principal you can become."""
    name = str(principal or "").lower()
    return any(token in name for token in OPEN_PRINCIPALS)


def lab_targets(template: dict) -> set[str]:
    """What a step can require besides a technique id.

    Not every prerequisite is a vuln id. ESC4 is modelled as an ACL on a
    certificate template, an ACL abuse chain is a list of edges, and a trust
    attack needs a second domain to exist at all. So a marker may also name:

    - a **host or domain** the lab contains (`lab-requires: meereen`), and
    - a **structural fact** about the lab's shape:
      `acls` (an ACL abuse *chain* is planted), `multi_domain` (more than one
      domain), `multi_host` (more than one attackable Windows host),
      `member_server` (a non-DC server), `workstation`.

    `acls` deliberately ignores grants to the anonymous and everyone principals.
    Those configure anonymous LDAP reads, which part 2 already covers as
    enumeration; they are not an escalation an ACL page can walk. minilab plants
    exactly two of them and nothing else, so counting any edge at all would hand
    it a part 11 with no chain in it.

    Structural facts are kept out of `lab_surface` on purpose: that function's
    count is the published technique surface and has to keep matching the lab
    matrix, so it must not grow tokens that are not techniques.
    """
    targets: set[str] = set()
    domains = 0
    windows_hosts = 0
    for node in template.get("nodes", []):
        overlay = node.get("overlay") or {}
        kind = node.get("kind")
        for key in ("hostname", "fqdn", "netbios"):
            value = overlay.get(key)
            if value:
                targets.add(str(value).lower())
        if node.get("id"):
            targets.add(str(node["id"]).lower())
        if any(not _is_open_principal(acl.get("principal")) for acl in overlay.get("acls") or []):
            targets.add("acls")
        if kind == "domain":
            domains += 1
        if kind in ("dc", "srv", "wks"):
            windows_hosts += 1
        if kind == "srv":
            targets.add("member_server")
        if kind == "wks":
            targets.add("workstation")
    if domains > 1:
        targets.add("multi_domain")
    if windows_hosts > 1:
        targets.add("multi_host")
    return targets


def split_sections(text: str) -> tuple[str, list[tuple[str, str]]]:
    """Return the preamble and the list of (heading, body) H2 sections."""
    lines = text.splitlines(keepends=True)
    preamble: list[str] = []
    sections: list[tuple[str, list[str]]] = []
    for line in lines:
        match = HEADING.match(line.rstrip("\n"))
        if match:
            sections.append((match.group(1).strip(), [line]))
        elif sections:
            sections[-1][1].append(line)
        else:
            preamble.append(line)
    return "".join(preamble), [(h, "".join(b)) for h, b in sections]


def requirements(block: str) -> list[str]:
    """Technique ids a block declares, flattened across every marker in it."""
    needed: list[str] = []
    for match in MARKER.finditer(block):
        needed.extend(part.strip().lower() for part in match.group(1).split(",") if part.strip())
    return needed


def only_for(block: str) -> list[str]:
    """Labs a block is exclusive to, empty when it is shared by all of them."""
    labs: list[str] = []
    for match in ONLY.finditer(block):
        labs.extend(part.strip().lower() for part in match.group(1).split(",") if part.strip())
    return labs


def strip_markers(text: str) -> str:
    """Markers are scaffolding for this tool, not content for the reader."""
    out = ONLY.sub("", MARKER.sub("", text))
    return re.sub(r"\n{3,}", "\n\n", out)


def render_sections(
    sections: list[tuple[str, str]], lab: str, surface: set[str]
) -> tuple[list[str], list[str]]:
    """Split sections into what this lab keeps and what it cannot reach."""
    kept: list[str] = []
    dropped: list[str] = []
    for heading, body in sections:
        exclusive = only_for(body)
        if exclusive and lab not in exclusive:
            # Another lab's material. Absent here, but never owed here either,
            # so it is not reported to the reader as something removed.
            continue
        needs = requirements(body)
        if needs and not (set(needs) & surface):
            dropped.append(f"{heading} (needs `{'` or `'.join(needs)}`)")
        else:
            kept.append(strip_markers(body))
    return kept, dropped


def render_part(source: Path, lab: str, surface: set[str]) -> tuple[str, list[str]] | None:
    """Render one part for one lab, or None when the whole part is N/A."""
    text = source.read_text(encoding="utf-8")
    preamble, sections = split_sections(text)

    part_needs = requirements(preamble)
    if part_needs and not (set(part_needs) & surface):
        return None

    kept, dropped = render_sections(sections, lab, surface)

    if not kept:
        return None

    if dropped:
        note = (
            f"{len(dropped)} step(s) from the source page are not reachable on "
            "this lab and were removed; they are listed at the end."
        )
    else:
        note = "Every step of the source page applies to this lab."

    banner = BANNER.format(lab=lab, source=f"../goad/{source.name}", dropped_note=note)
    body = strip_markers(preamble).rstrip("\n")
    # The banner goes under the title so the page still opens with its heading.
    if body.startswith("# "):
        title, _, rest = body.partition("\n")
        body = f"{title}\n\n{banner}\n{rest.lstrip(chr(10))}"
    else:
        body = f"{banner}\n{body}"

    out = [body.rstrip("\n"), ""]
    out.extend(section.rstrip("\n") + "\n" for section in kept)

    if dropped:
        out.append("\n## Not on this lab\n")
        out.append(
            "These steps are in the full GOAD series but need techniques this\n"
            "lab does not carry. They are listed so nothing looks missing:\n"
        )
        out.extend(f"- {item}" for item in dropped)
        out.append("")

    rendered = re.sub(r"\n{3,}", "\n\n", "\n".join(out))
    return rendered.rstrip("\n") + "\n", dropped


def retarget_links(content: str, present: set[str]) -> str:
    """Point sibling links at the source series when this lab has no such part.

    The pages cross-reference each other by filename. A lab that does not reach
    part 6 still has pages that link to it, and a link to a file this folder does
    not contain is a 404 for the reader. Those links are sent to the authored
    series instead, which is the honest destination: the part exists, just not
    on this lab.
    """

    def fix(match: re.Match[str]) -> str:
        target, anchor = match.group(1), match.group(2) or ""
        if target in present:
            return match.group(0)
        return f"](../goad/{target}{anchor})"

    return PART_LINK.sub(fix, content)


def render_index(lab: str, rows: list[tuple[str, str, str]], surface: set[str]) -> str:
    """The lab's own README: what applies, what does not, and why."""
    applies = sum(1 for _, status, _ in rows if status != "not on this lab")
    lines = [
        f"# GOAD series for `{lab}`",
        "",
        f"**Generated. Do not edit this folder by hand** - it is produced from",
        "[the authored GOAD series](../goad/README.md) by",
        "`python -m redstackpro.tools.gen_solutions`, filtered to what this lab actually",
        "carries. Edit the source pages, not these.",
        "",
        f"The `{lab}` lab carries **{len(surface)} techniques** and reaches",
        f"**{applies} of the {len(rows)} parts**. Read your deploy's own",
        "`HAVEN-BRIEFING.md` for the hosts, addresses and credentials, which are",
        "per deploy and not in these pages.",
        "",
        "| part | on this lab | note |",
        "|------|-------------|------|",
    ]
    for name, status, note in rows:
        link = f"[{name}]({name})" if status != "not on this lab" else name
        lines.append(f"| {link} | {status} | {note} |")
    lines.append("")
    return "\n".join(lines)


def generate(lab: str, check: bool) -> int:
    template_path = TEMPLATE_DIR / f"{lab}.json"
    if not template_path.exists():
        print(f"{lab}: no template at {template_path}", file=sys.stderr)
        return 2

    template = json.loads(template_path.read_text(encoding="utf-8"))
    techniques = lab_surface(template)
    surface = techniques | lab_targets(template)
    out_dir = SOLUTIONS_DIR / lab
    sources = sorted(p for p in SOURCE_DIR.iterdir() if PART_FILE.match(p.name))

    wanted: dict[str, str] = {}
    rows: list[tuple[str, str, str]] = []
    for source in sources:
        result = render_part(source, lab, surface)
        if result is None:
            rows.append((source.name, "not on this lab", "no step it carries is reachable here"))
            continue
        content, dropped = result
        wanted[source.name] = content
        if dropped:
            rows.append((source.name, "partial", f"{len(dropped)} step(s) removed"))
        else:
            rows.append((source.name, "yes", ""))

    present = set(wanted)
    wanted = {name: retarget_links(content, present) for name, content in wanted.items()}
    wanted["README.md"] = render_index(lab, rows, techniques)

    if check:
        stale: list[str] = []
        existing = {p.name for p in out_dir.iterdir()} if out_dir.exists() else set()
        for name, content in wanted.items():
            path = out_dir / name
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(name)
        for extra in sorted(existing - set(wanted)):
            stale.append(f"{extra} (no longer generated)")
        if stale:
            print(f"{lab}: out of date: {', '.join(stale)}", file=sys.stderr)
            return 1
        print(f"{lab}: up to date ({len(wanted) - 1} parts)")
        return 0

    # An empty surface is an input problem, never a shape: every shipped lab
    # reaches at least two techniques, and the smallest reaches two. It is what
    # a renamed overlay key looks like from in here, and the next lines DELETE,
    # so a surface that quietly came up empty would otherwise take most of the
    # committed series with it and exit 0.
    #
    # The floor is the surface and not the part count, because a part carrying
    # no marker is kept for every lab by design: with the surface emptied
    # entirely, four parts still render and the count never reaches zero. Tried
    # that way first and it let nine files go.
    parts = len(wanted) - 1
    if not surface:
        print(f"{lab}: the surface read from {template_path.name} is empty, "
              f"which no lab has. A renamed overlay key looks like this. "
              f"Refusing, because the next step deletes.", file=sys.stderr)
        return 2

    out_dir.mkdir(parents=True, exist_ok=True)
    removed = sorted({p.name for p in out_dir.iterdir()} - set(wanted)) if out_dir.exists() else []
    for extra in removed:
        (out_dir / extra).unlink()
    for name, content in wanted.items():
        (out_dir / name).write_text(content, encoding="utf-8", newline="\n")
    print(f"{lab}: wrote {parts} parts + README ({len(techniques)} techniques)")
    # Removing a part is a legitimate outcome: filtering goad-mini on lab shape
    # correctly took it from 14 parts to 5. But the run used to report only what
    # it wrote, so a drop from a surface that quietly shrank looked exactly like
    # a normal run. Name what went, and say how many are left to compare against.
    if removed:
        print(f"{lab}: removed {len(removed)} file(s): {', '.join(removed)}",
              file=sys.stderr)
    return 0


def main_check() -> int:
    """Staleness gate, for CI and the test suite."""
    return max(generate(lab, check=True) for lab in GENERATED_LABS)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--lab", action="append", help="lab to generate (default: all generated labs)")
    parser.add_argument("--check", action="store_true", help="fail if the committed output is stale")
    args = parser.parse_args()

    labs = args.lab or list(GENERATED_LABS)
    return max(generate(lab, args.check) for lab in labs)


if __name__ == "__main__":
    raise SystemExit(main())
