---
- name: Restart logstash
  ansible.builtin.service:
    name: logstash
    state: restarted

- name: Restart opensearch
  ansible.builtin.service:
    name: opensearch
    state: restarted

- name: Restart elasticsearch
  ansible.builtin.service:
    name: elasticsearch
    state: restarted

- name: Restart opensearch dashboards
  ansible.builtin.service:
    name: opensearch-dashboards
    state: restarted
