"""The AWS backend.

The module blocks are mechanical: a node becomes a module call the same way it
does on GCP. The firewall is not.

GCP restricts a source by network tag. A tag is a string, so a rule names a host
without depending on the host resource, and one rule carries a list of sources.
AWS restricts by security group reference, so the group has to exist as a
resource before a rule can point at it, and a rule carries exactly one source.
Three senders to one collector is one rule on GCP and three here.

That is the provider abstraction leaking, and 0015 says it leaks here.
"""

from .plan import (  # noqa: F401  GenerationError re-exported
    GenerationError, align, operator_hosts_hcl, time_provider)

# AMI owners and name patterns rather than ids, because an id is per region and
# the region is a variable. The module resolves them with a data source.
# Debian 13, not 12: 12 ships Python 3.11 and certipy-ad 5.x requires 3.12, so
# the toolkit silently fell back to a 4.x build that could not even start. See
# the note in gcp.py. Same Debian-owned account; only the name pattern moves.
DEFAULT_IMAGES = {
    "debian": ("136693071363", "debian-13-amd64-*"),
    # Kali publishes its own images, so os kali gets a real Kali box on AWS the
    # same as it does on GCP. The listing needs a one time subscription on the
    # account, which is an account action rather than something an export can
    # do: redStackPRO generates code and touches no account. The README says so.
    # The name carries a debian- prefix (the images are Debian-derived) and the
    # owner is the Marketplace publisher the subscription grants access under.
    "kali": ("679593333241", "debian-kali-last-snapshot-amd64-*"),
    "windows": ("amazon", "Windows_Server-2022-English-Full-Base-*"),
}

# The AD range names a specific Windows Server build per host. Each maps to the
# Marketplace base image for that build; an unrecognized or unset build falls
# back to 2022, the same default the attack side's bare "windows" resolves to.
#
# 2016 is pinned to the 2019 base image on purpose: Windows Server 2016 reaches
# Microsoft end-of-support on 2027-01-12, after which AWS stops publishing the
# 2016 base AMI and the data-source lookup would return no results. Forcing 2016
# to 2019 keeps every lab that still names 2016 (a shipped template or a custom
# range) deployable, with the closest behaviour and least default hardening.
WINDOWS_IMAGES = {
    "windows_server_2016": ("amazon", "Windows_Server-2019-English-Full-Base-*"),
    "windows_server_2019": ("amazon", "Windows_Server-2019-English-Full-Base-*"),
    "windows_server_2022": ("amazon", "Windows_Server-2022-English-Full-Base-*"),
}

DEFAULT_MACHINE = {
    "collector": "t3.large",
    "operator": "t3.large",
    # AD hosts. A DC promotion and a member join are memory hungry; a workstation
    # is lighter. A SIEM ingests and indexes, so it matches the collector.
    "dc": "t3.large",
    "srv": "t3.large",
    "wks": "t3.medium",
    "siem": "t3.large",
}


def image_for(plan, node):
    kind, overlay = node["kind"], node.get("overlay", {})
    if kind == "operator":
        return DEFAULT_IMAGES[overlay.get("os", "debian")]
    # A DC, member server, or workstation is Windows unless its os says otherwise
    # (a Linux member such as GOAD's lx01/syrax, or a SIEM). is_windows already
    # encodes that default: the AD host kinds are Windows when no os is set, and a
    # host whose os names linux is not.
    if plan.is_windows(node):
        return WINDOWS_IMAGES.get(overlay.get("os"), DEFAULT_IMAGES["windows"])
    return DEFAULT_IMAGES["debian"]


def files(plan):
    return {
        "terraform/versions.tf": _versions(plan),
        "terraform/variables.tf": _variables(plan.region),
        "terraform/terraform.tfvars": _tfvars(plan),
        "terraform/main.tf": _main(plan),
        "terraform/firewall.tf": _firewall(plan),
    }


# ---------------------------------------------------------------- static parts

def _versions(plan):
    return """# Generated by redStackPRO. Do not edit.
# redStackPRO does not run Terraform and does not bundle the binary. See 0001, 0002.

terraform {
  required_version = ">= 1.5"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.0"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0"
    }%s
  }
}""" % time_provider(plan) + """

provider "aws" {
  region = var.region
}
"""


def _variables(region="us-east-1"):
    return """# Generated by redStackPRO. Do not edit.
# Values live in terraform.tfvars. Credentials and key material never do.

variable "region" {
  type    = string
  default = "%s"
}""" % region + """

variable "availability_zone" {
  description = "Zone for every subnet. Null takes the first in the region, which is stable because the list is sorted. Set it to place the range deliberately."
  type        = string
  default     = null
}

variable "ssh_public_key" {
  description = "Authorized key for the admin account, supplied at run time."
  type        = string
}

variable "key_name" {
  description = "Name of the key pair this export creates from ssh_public_key."
  type        = string
  default     = "redstackpro"
}

variable "operator_source_ranges" {
  description = "Where management access is accepted from. Narrow this."
  type        = list(string)
  default     = ["0.0.0.0/0"]
}

variable "lab_password" {
  description = "One shared lab password for the admin account, the Windows operator, and the Guacamole login. Left empty, a strong one is generated at apply and printed in the outputs. Never in the export."
  type        = string
  default     = ""
  sensitive   = true
}
"""


def _tfvars(plan):
    return """# Generated by redStackPRO. Fill these in before running terraform.
# Never commit this file with real values. See the project conventions.

region         = "us-east-1"
ssh_public_key = ""

# Narrow this to the addresses operators connect from.
operator_source_ranges = ["0.0.0.0/0"]
"""


# ---------------------------------------------------------------- root module

def _main(plan):
    lines = [
        "# Generated by redStackPRO. Do not edit.",
        "# One module block per node. Inter module references resolve at apply",
        "# time on your machine, because redStackPRO never runs Terraform. See 0001.",
        "",
        "# One key pair for the export. The key itself is a variable and is",
        "# never generated or stored here. See 0001.",
        'resource "aws_key_pair" "redstackpro" {',
        "  key_name   = var.key_name",
        "  public_key = var.ssh_public_key",
        "}",
        "",
        "# One shared lab password, generated at apply unless the operator set one.",
        "# It is never in the export: it lives in your state and on your own boxes.",
        'resource "random_password" "lab" {',
        "  length           = 20",
        "  special          = true",
        '  override_special = "!@#-_=+"',
        "}",
        "",
        "# A key pair the jumpbox uses to reach every box for the Guacamole tiles.",
        "# The public half is authorized on each box at boot; the private half goes",
        "# to the jumpbox, so the portal connects with no password on the wire.",
        'resource "tls_private_key" "guacamole" {',
        '  algorithm = "ED25519"',
        "}",
        "",
        "# One zone for every subnet. Left to AWS each subnet gets whichever",
        "# zone it is given, so two applies differ and traffic that should be",
        "# local crosses zones and bills for it. The list is sorted, so the",
        "# default is stable for a region rather than merely arbitrary.",
        'data "aws_availability_zones" "available" {',
        '  state = "available"',
        "}",
        "",
        "locals {",
        "  availability_zone = coalesce(",
        "    var.availability_zone,",
        "    data.aws_availability_zones.available.names[0],",
        "  )",
        "  # The operator's password if they set one, otherwise the generated one.",
        "  lab_password = var.lab_password != \"\" ? var.lab_password : random_password.lab.result",
        "}",
    ]

    for node in plan.networks():
        nid = node["id"]
        # Internal hosts (teamservers, operators, collectors) take no public
        # address, so their outbound rides a NAT gateway rather than the internet
        # gateway. The gateway is built only when a segment actually needs it
        # (segment_needs_nat), because it bills by the hour; its subnet is carved
        # from a range no segment occupies. See 0021.
        needs_nat = plan.needs_nat(nid)
        # An addressed host cannot live in a NAT-routed subnet on AWS: one route
        # table serves the whole subnet, so pointing it at the NAT for the internal
        # hosts leaves the addressed one unable to answer inbound. It goes in the
        # public subnet instead, which is the same subnet the NAT gateway needs, so
        # one is enough. See public_hosts and 0021.
        public_hosts = plan.public_hosts_in_network(nid)
        pairs = [
            ("source", '"./modules/aws/network"'),
            ("name", '"%s"' % plan.tag(nid)),
            ("cidr", '"%s"' % node["overlay"]["cidr"]),
            ("availability_zone", "local.availability_zone"),
            ("create_nat", "true" if needs_nat else "false"),
            ("create_public_subnet", "true" if public_hosts else "false"),
        ]
        if needs_nat or public_hosts:
            pairs.append(("public_subnet_cidr", '"%s"' % plan.spare_subnet(nid)))
        lines += ["", 'module "%s" {' % plan.ref(nid)] + align(pairs) + ["}"]

    for node in plan.segments():
        network = plan.ctx.network_of_segment(node["id"])
        overlay = node["overlay"]
        lines += ["", 'module "%s" {' % plan.ref(node["id"])] + align([
            ("source", '"./modules/aws/segment"'),
            ("name", '"%s"' % plan.tag(node["id"])),
            ("vpc_id", "module.%s.id" % plan.ref(network)),
            ("cidr", '"%s"' % overlay["cidr"]),
            ("availability_zone", "local.availability_zone"),
            ("egress", '"%s"' % overlay["egress"]),
            ("exposure", '"%s"' % overlay["exposure"]),
            # A subnet holding any host without a public address routes its
            # outbound through the NAT gateway; a public subnet (jumpbox,
            # redirector) keeps the internet gateway. segment_needs_nat sees the
            # members, which exposure alone cannot. See 0021.
            ("nat", "true" if plan.segment_needs_nat(node["id"]) else "false"),
            ("internet_gateway_id",
             "module.%s.internet_gateway_id" % plan.ref(network)),
            ("nat_gateway_id", "module.%s.nat_gateway_id" % plan.ref(network)),
        ]) + ["}"]

    # The range turns itself off, so an operator who forgets does not pay for a
    # weekend. AWS has no per-instance schedule -- no answer to GCP's resource
    # policy or Azure's shutdown setting -- so the stop is one EventBridge
    # schedule calling ec2:StopInstances with an explicit list of ids.
    #
    # The universal target (arn:aws:scheduler:::aws-sdk:ec2:stopInstances) calls
    # the SDK directly, so there is no Lambda to write, deploy or pay for. The
    # permission lives in a role EventBridge assumes, NOT a credential on any
    # host -- in particular not on the jumpbox, which is the range's only public
    # box and stays credential-free (minimize-jumpbox-web-surface).
    #
    # STOP, never terminate: the forest took forty minutes to provision and comes
    # back on boot. See 0057.
    #
    # NOTE this is the stack's first IAM resource. An operator whose credentials
    # cannot create roles will fail the apply here, and the error names this
    # resource, which is why it is one role with one action rather than anything
    # broader.
    stop = plan.auto_stop
    hosts = list(plan.hosts())
    if stop and hosts:
        ids = ",\n".join("        module.%s.instance_id" % plan.ref(h["id"])
                         for h in hosts)
        prefix = plan.topology.get("prefix", "red")
        lines += plan.auto_stop_block()
        lines += [
            "",
            "# Auto stop. One schedule for the whole range.",
            'resource "aws_iam_role" "auto_stop" {',
            '  name = "%s-auto-stop"' % prefix,
            "  assume_role_policy = jsonencode({",
            '    Version = "2012-10-17"',
            "    Statement = [{",
            '      Effect    = "Allow"',
            '      Action    = "sts:AssumeRole"',
            '      Principal = { Service = "scheduler.amazonaws.com" }',
            "    }]",
            "  })",
            "}",
            "",
            'resource "aws_iam_role_policy" "auto_stop" {',
            '  name = "%s-auto-stop"' % prefix,
            "  role = aws_iam_role.auto_stop.id",
            "  policy = jsonencode({",
            '    Version = "2012-10-17"',
            "    Statement = [{",
            '      Effect = "Allow"',
            '      Action = "ec2:StopInstances"',
            "      Resource = [",
            ",\n".join('        "arn:aws:ec2:${var.region}:*:instance/${module.%s.instance_id}"'
                       % plan.ref(h["id"]) for h in hosts),
            "      ]",
            "    }]",
            "  })",
            "}",
            "",
            'resource "aws_scheduler_schedule" "auto_stop" {',
            '  name                         = "%s-auto-stop"' % prefix,
            '  schedule_expression          = "cron(%s %s * * ? *)"'
            % (stop["minute_tpl"], stop["hour_tpl"]),
            # AWS takes an IANA name, the same vocabulary GCP uses, so the
            # canvas value passes straight through. Azure is the odd one out.
            '  schedule_expression_timezone = "%s"' % stop["timezone"],
            "",
            "  flexible_time_window {",
            '    mode = "OFF"',
            "  }",
            "",
            "  target {",
            '    arn      = "arn:aws:scheduler:::aws-sdk:ec2:stopInstances"',
            "    role_arn = aws_iam_role.auto_stop.arn",
            "    input = jsonencode({",
            "      InstanceIds = [",
            ids,
            "      ]",
            "    })",
            "  }",
            "}",
        ]

    for node in plan.hosts():
        segment = plan.primary_segment(node)
        network = plan.ctx.network_of_segment(segment)
        owner, pattern = image_for(plan, node)
        takes_public = plan.takes_public_address(node)
        # An addressed host goes in the network's public subnet, not its segment's.
        # AWS gives a subnet ONE route table: the segment's points at the NAT
        # gateway for the internal hosts, and an addressed host sharing it cannot
        # answer inbound, because its replies leave through the NAT. That is a
        # silent break, and it made every AWS range unreachable at its jumpbox.
        # GCP needs none of this: Cloud NAT serves only instances without an
        # external address, so routing is effectively per instance there.
        subnet_ref = ("module.%s.public_subnet_id" % plan.ref(network)
                      if takes_public
                      else "module.%s.subnet_id" % plan.ref(segment))
        pairs = [
            ("source", '"./modules/aws/host"'),
            ("name", '"%s"' % plan.tag(node["id"])),
            ("node_id", '"%s"' % plan.tag(node["id"])),
            ("kind", '"%s"' % node["kind"]),
            ("vpc_id", "module.%s.id" % plan.ref(network)),
            ("subnet_id", subnet_ref),
            ("image_owner", '"%s"' % owner),
            ("image_name", '"%s"' % pattern),
            # Only internet-facing hosts take a public address: the redirector
            # (C2 ingress) and a range's jumpbox (Guacamole + ssh). Everything
            # else -- teamservers, operators, collectors -- stays private with no
            # public IP, so it cannot be scanned or reached from the internet at
            # all, and egresses through the NAT gateway. Matches the GCP model.
            # See 0021.
            ("public_address", "true" if takes_public else "false"),
            ("key_name", "aws_key_pair.redstackpro.key_name"),
            # The single platform account (redop for ops, blueop for a range);
            # cloud-init creates it and authorizes the keys for it. See P1.7.
            ("admin_username", '"%s"' % plan.admin_account),
            # The key pair lands only on the image default account. cloud-init in
            # the host module uses this to create the admin account the Ansible
            # layer connects as, the AWS analogue of the GCP ssh-keys metadata.
            ("ssh_public_key", "var.ssh_public_key"),
            # A fresh Windows image has no WinRM listener, so the host module
            # stands one up. Without it the operators play cannot connect at
            # all. See 0019.
            ("windows", "true" if plan.is_windows(node) else "false"),
            # A range's controllers and members are provisioned over WinRM, so
            # the boot script sets the Administrator password and an HTTPS
            # listener. An offense range's Windows operator self-provisions and
            # is left alone. See goad-native-recreation.
            ("enable_winrm",
             "true" if (plan.is_range() and plan.is_windows(node)) else "false"),
            # A stable Elastic IP for the two hosts reached from outside, so their
            # address holds across a stop and start; a redirector's DNS keeps
            # resolving and a jumpbox stays where operators point. Every other
            # host keeps its auto-assigned public address, used only for outbound.
            ("elastic_ip",
             "true" if node["kind"] in ("jumpbox", "redirector") else "false"),
            # The shared lab password (the admin account here, the Windows operator on a
            # Windows box) and the Guacamole key material. The jumpbox alone gets
            # the private half; every box authorizes the public half for the admin account.
            ("lab_password", "local.lab_password"),
            # The Windows local account and the Guacamole login are the same
            # single platform identity as the Linux admin (redop for ops, blueop
            # for a range), not a separate "operator". The module input keeps its
            # name; the value it now carries is the platform account. See P1.7 and
            # naming.platform_account.
            ("operator_username", '"%s"' % plan.admin_account),
            ("guac_public_key", "tls_private_key.guacamole.public_key_openssh"),
            ("guac_private_key",
             "tls_private_key.guacamole.private_key_openssh"
             if node["kind"] == "jumpbox" else '""'),
        ]
        machine = DEFAULT_MACHINE.get(node["kind"])
        if machine:
            pairs.append(("instance_type", '"%s"' % machine))
        # Exchange needs room for a 6 GB ISO plus a large install; the module's
        # default 30 GB cannot hold it. Give an Exchange host a bigger disk.
        if "exchange" in (node.get("overlay", {}).get("services") or []):
            pairs.append(("disk_size_gb", "120"))
        # A range locking this host to a specific address (GOAD's canonical
        # octets, see 0055); omitted lets AWS assign one from the subnet's
        # range, the unchanged default.
        #
        # An addressed host is the exception: it sits in the public subnet, whose
        # range is carved from spare space in the network and has nothing to do
        # with the segment the pin was written against. Honouring the pin there
        # would fail at apply for an address outside the subnet, so it is dropped
        # and AWS assigns one. The pinned octets that matter for fidelity are the
        # AD hosts', and those stay in the segment. See 0055.
        internal_ip = node.get("overlay", {}).get("internal_ip")
        if internal_ip and not takes_public:
            pairs.append(("private_ip", '"%s"' % internal_ip))
        # The offense Windows operator self-provisions its kit at boot (it has no
        # WinRM and Ansible never reaches it), so it takes the operator setup
        # script -- encoded to ride inside user_data, since the script has
        # here-strings of its own -- plus a hosts block for its MobaXterm
        # sessions. Ops-mode only: a range's Windows hosts are driven by Ansible.
        #
        # base64GZIP, not base64encode. AWS caps user_data at 16384 bytes, and
        # plain base64 of this script is 13808 of them; with the boot wrapper
        # around it that is ~18.6KB, and apply fails with "expected length of
        # user_data to be in the range (0 - 16384)". Gzip takes the payload to
        # ~5.3KB. The boot template decompresses it. GCP puts the same script in
        # a metadata key with a 256KB budget, so only AWS needs this.
        if (not plan.is_range() and node["kind"] == "operator"
                and plan.is_windows(node)):
            pairs += [
                ("operator_setup", "true"),
                ("operator_setup_script_b64",
                 'base64gzip(file("${path.module}/scripts/operator_setup.ps1"))'),
                ("operator_hosts", operator_hosts_hcl(plan)),
                # The same key the jumpbox uses: its public half is already an
                # authorized key for the platform account on every host, so the
                # operator box can key-auth into the stack and MobaXterm stops
                # prompting for the password. Password auth stays on as the
                # fallback. ED25519, so it is tiny inside user_data.
                ("operator_ssh_key",
                 "tls_private_key.guacamole.private_key_openssh"),
            ]
        lines += ["", 'module "%s" {' % plan.ref(node["id"])] + align(pairs) + ["}"]

    # peers: a VPC peering plus a route to the peer CIDR in every segment route
    # table on each side, because AWS does not exchange routes on its own. See
    # 0031.
    #
    # "Every route table" has to include the PUBLIC one, not just the segments'.
    # A public-addressed host does not live in a segment subnet on AWS (0054) --
    # it is relocated into the network's public subnet, which has a route table
    # of its own carrying only a local route and a default route to the internet
    # gateway. Leave it out and such a host reaches the internet and its own VPC
    # but nothing across the peering, with the peering active and looking
    # healthy. That is precisely how the ops jumpbox lost SSH to its redirector.
    ctx = plan.ctx

    def _tables(network_id):
        refs = ["module.%s.route_table_id" % plan.ref(s["id"])
                for s in plan.segments_in(network_id)]
        # Include the public route table ONLY when this network actually builds
        # one -- the same condition the network module gates it on (a NAT or a
        # public subnet). Deciding it here, at compile, rather than with a
        # compact(try(...,null)) at apply, is what keeps the list a statically
        # known length: the peering module's `count = length(route_tables)` needs
        # that, and compact() of a maybe-null id made the count unknown at plan
        # ("Invalid count argument"). Caught by a fresh deploy -- the live range
        # never hit it because its peer routes were added by hand, not terraform.
        if plan.needs_nat(network_id) or plan.public_hosts_in_network(network_id):
            refs.append(
                "module.%s.public_route_table_id" % plan.ref(network_id))
        return "[%s]" % ", ".join(refs)

    for edge in ctx.by_role.get("peers", []):
        a, b = edge["source"], edge["target"]
        tables_a = _tables(a)
        tables_b = _tables(b)
        lines += ["", 'module "%s" {' % plan.ref(edge["id"])] + align([
            ("source", '"./modules/aws/peering"'),
            ("name", '"%s"' % plan.tag(edge["id"])),
            ("vpc_a", "module.%s.id" % plan.ref(a)),
            ("vpc_b", "module.%s.id" % plan.ref(b)),
            ("cidr_a", '"%s"' % ctx.overlay(a, "cidr")),
            ("cidr_b", '"%s"' % ctx.overlay(b, "cidr")),
            ("route_tables_a", tables_a),
            ("route_tables_b", tables_b),
        ]) + ["}"]

    # The portal address and the operator credentials, printed at apply. They are
    # generated here rather than in the export, so this is where they surface.
    jumps = [n for n in plan.hosts() if n["kind"] == "jumpbox"]
    if jumps:
        jref = plan.ref(jumps[0]["id"])
        lines += [
            "",
            'output "guacamole" {',
            '  description = "The single pane of glass. Open the url and log in."',
            "  sensitive   = true",
            "  value = {",
            '    url      = "https://${module.%s.public_address}/guacamole"' % jref,
            '    username = "%s"' % plan.admin_account,
            "    password = local.lab_password",
            "  }",
            "}",
        ]
    lines += [
        "",
        'output "lab_password" {',
        '  description = "Shared password for the admin account, the Windows operator, and the portal."',
        "  sensitive   = true",
        "  value       = local.lab_password",
        "}",
    ]

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------- firewall

def _ingress(name, target_ref, protocol, port, source_group=None,
             source_cidr=None, source_expr=None, comment=None):
    """One rule, one source. That is the AWS shape and it is why a fan in that
    is one rule on GCP is several here."""
    lines = []
    if comment:
        lines.append("# %s" % comment)
    lines.append(
        'resource "aws_vpc_security_group_ingress_rule" "%s" {' % name)

    pairs = []
    if source_expr:
        # A variable length list is expanded at apply time, because its contents
        # are not known when this file is written.
        pairs.append(("for_each", "toset(%s)" % source_expr))
    pairs += [
        ("security_group_id", "module.%s.security_group_id" % target_ref),
        ("ip_protocol", '"%s"' % protocol),
    ]
    # Protocol -1 is every protocol and every port, and AWS rejects a port range
    # on it. Any other protocol names a single port.
    if protocol != "-1":
        pairs += [("from_port", str(port)), ("to_port", str(port))]
    if source_expr:
        pairs.append(("cidr_ipv4", "each.value"))
    if source_cidr:
        pairs.append(("cidr_ipv4", '"%s"' % source_cidr))
    if source_group:
        pairs.append(("referenced_security_group_id",
                      "module.%s.security_group_id" % source_group))
    if comment:
        pairs.append(("description", '"%s"' % comment))

    lines += align(pairs)
    lines.append("}")
    return lines


def _firewall(plan):
    """Rules come from edges. A node cannot know them; only a drawn line can."""
    ctx = plan.ctx
    lines = [
        "# Generated by redStackPRO. Do not edit.",
        "# Every rule below exists because of an edge in the topology. Source",
        "# restriction is derived from those edges rather than from segment",
        "# ranges, so a rule names exactly the hosts that need it.",
        "#",
        "# Egress is open at the security group and decided by the route table,",
        "# which is what the segment egress field renders into. The GCP backend",
        "# has the same shape: open by default, and NAT decides whether it goes",
        "# anywhere.",
    ]
    seen = set()

    # OPS MODE ONLY: the stack's own hosts reach each other freely.
    #
    # An offense platform is the operator's own infrastructure, not a target.
    # Segmenting it buys nothing to defend against and costs real friction: the
    # Windows operator box could not SSH the teamservers its own saved sessions
    # point at, and the jumpbox could not reach its redirector. The original
    # redStack gives every host an all-from-VPC rule (protocol -1, every port)
    # for exactly this reason, plus one for the peered redirector VPC.
    #
    # A RANGE keeps strictly edge-derived rules. There the segmentation IS the
    # exercise, so this deliberately does not apply. External ingress is
    # untouched in both modes, which is the property that actually matters.
    if not plan.is_range():
        stack_cidrs = [c for c in (ctx.overlay(n["id"], "cidr")
                                   for n in plan.networks()) if c]
        for node in plan.hosts():
            for cidr in stack_cidrs:
                name = "intra_%s_%s" % (plan.ref(node["id"]),
                                        cidr.replace(".", "_").replace("/", "_"))
                # No apostrophe: AWS rejects a security group rule description
                # containing one ("Invalid rule description"), which failed every
                # intra rule on the first fresh deploy.
                lines += [""] + _ingress(
                    name, plan.ref(node["id"]), "-1", None, source_cidr=cidr,
                    comment="%s reaches the operator stack (%s)"
                            % (ctx.name(node["id"]), cidr))

    def network_of(node_id):
        nets = ctx.networks_of(node_id)
        return nets[0] if nets else None

    def source_cidr(node_id):
        # The host's own subnet, for a rule that reaches it across a peering.
        # A security group reference across peered VPCs needs the connection
        # active first, so a CIDR sidesteps the apply ordering. See 0031.
        #
        # A host that takes a public address is NOT in its declared segment on
        # AWS. One route table serves a whole subnet, so an addressed host
        # cannot sit in the NAT-routed one and gets relocated into the network's
        # public subnet instead (see public_hosts and 0054). Naming the declared
        # segment here would therefore allow a CIDR the host is not in, and the
        # rule would deny the very traffic it was written for. This is exactly
        # how the ops jumpbox lost SSH to its redirector across the peering: the
        # rule allowed 10.30.0.0/24 while the jumpbox sat at 10.30.255.249.
        node = ctx.nodes[node_id]
        if plan.takes_public_address(node):
            network = network_of(node_id)
            if network:
                return plan.spare_subnet(network)
        return ctx.overlay(plan.primary_segment(node), "cidr")

    # fronts: public ingress to the redirector, then redirector to teamserver.
    for edge in ctx.by_role.get("fronts", []):
        rdir, ts = edge["source"], edge["target"]
        protocol = "tcp" if edge["protocol"] != "dns" else "udp"
        listen = edge["listen_port"]
        upstream = edge.get("upstream_port", listen)

        name = "in_%s_%s" % (plan.ref(rdir), listen)
        if name not in seen:
            seen.add(name)
            lines += [""] + _ingress(
                name, plan.ref(rdir), protocol, listen,
                source_cidr="0.0.0.0/0",
                comment="%s accepts operational traffic" % ctx.name(rdir))

        # Port 80 answers the ACME http-01 challenge that issues the redirector's
        # certificate and otherwise redirects to 443, so a plain-http visitor and
        # Let's Encrypt both reach it. See the redirector role.
        name80 = "in_%s_80" % plan.ref(rdir)
        if name80 not in seen:
            seen.add(name80)
            lines += [""] + _ingress(
                name80, plan.ref(rdir), "tcp", 80,
                source_cidr="0.0.0.0/0",
                comment="%s redirects http to https and answers ACME"
                        % ctx.name(rdir))

        name = "fwd_%s_%s" % (plan.ref(rdir), plan.ref(ts))
        if name not in seen:
            seen.add(name)
            # Same VPC names the redirector by its security group; across a
            # peering, by its subnet CIDR, since a group reference needs the
            # connection active first. See 0031.
            if network_of(rdir) == network_of(ts):
                lines += [""] + _ingress(
                    name, plan.ref(ts), protocol, upstream,
                    source_group=plan.ref(rdir),
                    comment="%s forwards to %s" % (ctx.name(rdir), ctx.name(ts)))
            else:
                lines += [""] + _ingress(
                    name, plan.ref(ts), protocol, upstream,
                    source_cidr=source_cidr(rdir),
                    comment="%s forwards to %s across a peering"
                            % (ctx.name(rdir), ctx.name(ts)))

    # An operator box drives a teamserver from inside the range over the C2's
    # control-plane port (Mythic's web UI, Sliver's multiplayer listener,
    # Adaptix's operator endpoint). The beacon channel itself rides the fronts
    # edge through the redirector above; this is the separate operator ->
    # teamserver management path that nothing else opens. One rule per
    # operator/port, because a security group rule takes one source. Same VPC
    # names the operator by its security group; across a peering, by its subnet
    # CIDR. Emitted only for a teamserver whose C2 has a known control port. See P7.
    operators = sorted(plan.operators(), key=lambda h: h["id"])
    for ts in sorted(plan.hosts(), key=lambda h: h["id"]):
        ports = plan.control_ports(ts)
        tsnet = network_of(ts["id"])
        if not ports or not tsnet:
            continue
        for op in operators:
            for port in ports:
                name = "ctl_%s_%s_%s" % (plan.ref(ts["id"]), plan.ref(op["id"]), port)
                if name in seen:
                    continue
                seen.add(name)
                if network_of(op["id"]) == tsnet:
                    lines += [""] + _ingress(
                        name, plan.ref(ts["id"]), "tcp", port,
                        source_group=plan.ref(op["id"]),
                        comment="%s drives %s on %d"
                                % (ctx.name(op["id"]), ctx.name(ts["id"]), port))
                elif source_cidr(op["id"]):
                    lines += [""] + _ingress(
                        name, plan.ref(ts["id"]), "tcp", port,
                        source_cidr=source_cidr(op["id"]),
                        comment="%s drives %s across a peering on %d"
                                % (ctx.name(op["id"]), ctx.name(ts["id"]), port))

    # logs_to: senders reach the collector on its ingest port and nothing else.
    # One rule per sender, because a security group rule takes one source.
    sinks = {}
    for edge in ctx.by_role.get("logs_to", []):
        sinks.setdefault(edge["target"], []).append(edge["source"])
    for collector, senders in sorted(sinks.items()):
        port = ctx.overlay(collector, "ingest_port", 5044)
        cnet = network_of(collector)
        for sender in sorted(senders):
            name = "log_%s_%s" % (plan.ref(collector), plan.ref(sender))
            if name in seen:
                continue
            seen.add(name)
            # Same VPC names the sender by its security group; across a peering,
            # by its subnet CIDR. See 0031.
            if network_of(sender) == cnet:
                lines += [""] + _ingress(
                    name, plan.ref(collector), "tcp", port,
                    source_group=plan.ref(sender),
                    comment="%s ships to %s, push over TCP with TLS"
                            % (ctx.name(sender), ctx.name(collector)))
            else:
                lines += [""] + _ingress(
                    name, plan.ref(collector), "tcp", port,
                    source_cidr=source_cidr(sender),
                    comment="%s ships to %s across a peering, push over TCP"
                            % (ctx.name(sender), ctx.name(collector)))

    # manages: operator access to the jumpbox, then jumpbox to what it manages.
    for edge in ctx.by_role.get("manages", []):
        jump = edge["source"]

        name = "mgmt_in_%s" % plan.ref(jump)
        if name not in seen:
            seen.add(name)
            lines += [""] + _ingress(
                name, plan.ref(jump), "tcp", 22,
                source_expr="var.operator_source_ranges",
                comment="operator access to %s" % ctx.name(jump))

        # The Guacamole portal runs on the jumpbox over HTTPS, so the operator
        # reaches it on 443 from the same ranges that get ssh.
        name = "guac_in_%s" % plan.ref(jump)
        if name not in seen:
            seen.add(name)
            lines += [""] + _ingress(
                name, plan.ref(jump), "tcp", 443,
                source_expr="var.operator_source_ranges",
                comment="operator access to the Guacamole portal on %s"
                        % ctx.name(jump))

        # The jumpbox is the range's initial-access foothold: it sits on the
        # range segment and must receive traffic range hosts initiate back to it
        # -- a coerced or relayed NTLM authentication landing on an operator
        # listener (ntlmrelayx/Responder), a pivoted callback. Without this its
        # only ingress is the operator's 22/443 and a coerced DC's SMB call back
        # to a relay listener is dropped. This is *internal* (range-segment)
        # surface, which a lab expects; the jumpbox's internet surface stays the
        # operator rules above. Mirrors the AD hosts' all-from-segment rule
        # below. See part-04 and gcp.py's foothold rule.
        name = "foothold_in_%s" % plan.ref(jump)
        scidr = source_cidr(jump)
        if name not in seen and scidr:
            seen.add(name)
            lines += [""] + _ingress(
                name, plan.ref(jump), "-1", None,
                source_cidr=scidr,
                comment="%s (range foothold) accepts traffic from its own "
                        "segment: coerced/relayed callbacks and pivot returns"
                        % ctx.name(jump))

        managed = sorted(
            (h for h in plan.hosts()
             if h["id"] != jump and ctx.manager_of(h["id"]) == jump),
            key=lambda h: h["id"])
        jnet = network_of(jump)
        for host in managed:
            base = "mgmt_out_%s_%s" % (plan.ref(jump), plan.ref(host["id"]))
            # A Windows host is reached over WinRM (22 opens nothing on it), and
            # guacd on the jumpbox also needs 3389 to render its RDP tile. See 0019.
            rules = [(base, plan.management_port(host))]
            if plan.is_windows(host):
                rules.append((base + "_rdp", 3389))
            for name, port in rules:
                if name in seen:
                    continue
                seen.add(name)
                # Same VPC names the jumpbox by its security group; across a
                # peering, by its subnet CIDR. See 0031.
                if network_of(host["id"]) == jnet:
                    lines += [""] + _ingress(
                        name, plan.ref(host["id"]), "tcp", port,
                        source_group=plan.ref(jump),
                        comment="%s manages %s on %d"
                                % (ctx.name(jump), ctx.name(host["id"]), port))
                else:
                    lines += [""] + _ingress(
                        name, plan.ref(host["id"]), "tcp", port,
                        source_cidr=source_cidr(jump),
                        comment="%s manages %s across a peering on %d"
                                % (ctx.name(jump), ctx.name(host["id"]), port))

    # joins: an AD domain. A domain talks to its controller and controllers
    # replicate over a wide, partly dynamic set of ports (Kerberos, LDAP and the
    # global catalog, SMB, DNS, the RPC endpoint mapper and its high dynamic
    # range) too many and too fluid to enumerate as one rule each. The lab subnet
    # is local and isolated, so every AD host accepts all traffic from its own
    # segment: that is how a member reaches its DC to join and how DCs replicate.
    # These rules exist only because a joins edge drew a domain. SIEM boxes get
    # the same all-from-segment rule so agents can reach their ingest ports.
    for host in plan.intra_segment_hosts():
        name = "ad_intra_%s" % plan.ref(host["id"])
        if name in seen:
            continue
        seen.add(name)
        lines += [""] + _ingress(
            name, plan.ref(host["id"]), "-1", None,
            source_cidr=source_cidr(host["id"]),
            comment="%s accepts intra-domain traffic from its segment"
                    % ctx.name(host["id"]))

        # The all-from-segment rule above is written against the segment's range,
        # but on AWS an addressed host does not sit in it: the jumpbox lives in the
        # public subnet, because a NAT-routed subnet cannot carry a public address.
        # Its traffic therefore arrives from outside the segment range and that rule
        # does not cover it -- which would silently block the whole point of the
        # foothold, every tool an operator runs from it against AD (SMB, LDAP,
        # Kerberos, RPC). Referencing the security group rather than a range keeps
        # it tight and independent of which subnet the jumpbox ended up in.
        hnet = network_of(host["id"])
        for jump in plan.hosts():
            if jump["kind"] != "jumpbox" or not plan.takes_public_address(jump):
                continue
            if network_of(jump["id"]) != hnet:
                continue
            jname = "ad_intra_%s_from_%s" % (plan.ref(host["id"]),
                                             plan.ref(jump["id"]))
            if jname in seen:
                continue
            seen.add(jname)
            lines += [""] + _ingress(
                jname, plan.ref(host["id"]), "-1", None,
                source_group=plan.ref(jump["id"]),
                comment="%s accepts traffic from the %s foothold, which sits in "
                        "the public subnet rather than the segment"
                        % (ctx.name(host["id"]), ctx.name(jump["id"])))

    return "\n".join(lines) + "\n"
