"""The ESXi / vSphere backend (hashicorp/vsphere).

On-prem like Proxmox, but vSphere has no cloud-image download and no managed
per-VM firewall. So (Michael's calls, 2026-08-28): a Linux host deploys from an
OVA URL the operator supplies, a Windows host clones a prepared template, and
segmentation is VLAN-only on port groups with no firewall resource (host-level or
appliance firewalling is the operator's, stated in firewall.tf). Each host takes
a static address from its segment, customized in at deploy. See 0015.
"""

import ipaddress

from .plan import GenerationError, align  # noqa: F401  GenerationError re-exported

DEFAULT_MACHINE = {
    "collector": (2, 4096),
    "operator": (2, 4096),
    "dc": (2, 4096),
    "srv": (2, 4096),
    "wks": (2, 2048),
    "siem": (4, 8192),
}


def is_windows(node):
    os_ = node.get("overlay", {}).get("os", "")
    if node["kind"] == "operator":
        return os_.startswith("windows")
    return os_.startswith("windows") or (
        node["kind"] in ("dc", "srv", "wks")
        and not os_.startswith(("debian", "ubuntu", "linux")))


def files(plan):
    return {
        "terraform/versions.tf": _versions(),
        "terraform/variables.tf": _variables(),
        "terraform/terraform.tfvars": _tfvars(),
        "terraform/main.tf": _main(plan),
        "terraform/firewall.tf": _firewall(plan),
    }


# ---------------------------------------------------------------- static parts

def _versions():
    return """# Generated by redStackPRO. Do not edit.
# redStackPRO does not run Terraform and does not bundle the binary. See 0001, 0002.

terraform {
  required_version = ">= 1.5"

  required_providers {
    vsphere = {
      source  = "hashicorp/vsphere"
      version = "~> 2.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.0"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0"
    }
  }
}

provider "vsphere" {
  user                 = var.vsphere_user
  password             = var.vsphere_password
  vsphere_server       = var.vsphere_server
  allow_unverified_ssl = var.vsphere_insecure
}
"""


def _variables():
    return """# Generated by redStackPRO. Do not edit.
# Values live in terraform.tfvars. Credentials and key material never do.

variable "vsphere_server" {
  description = "vCenter or ESXi hostname."
  type        = string
}

variable "vsphere_user" {
  description = "vSphere username, e.g. administrator@vsphere.local or root."
  type        = string
}

variable "vsphere_password" {
  description = "vSphere password, supplied at run time."
  type        = string
  sensitive   = true
}

variable "vsphere_insecure" {
  description = "Skip TLS verification of the vSphere endpoint (self-signed labs)."
  type        = bool
  default     = true
}

variable "datacenter" {
  description = "vSphere datacenter name."
  type        = string
  default     = "ha-datacenter"
}

variable "datastore" {
  description = "Datastore for VM disks."
  type        = string
}

variable "resource_pool" {
  description = "Resource pool to place VMs in. On a standalone ESXi host this is the host's root pool."
  type        = string
}

variable "esxi_host" {
  description = "ESXi host that owns the standard vSwitch the port groups ride on."
  type        = string
}

variable "vswitch" {
  description = "Standard vSwitch every segment port group is created on."
  type        = string
  default     = "vSwitch0"
}

variable "linux_ova_url" {
  description = "URL of a Linux cloud OVA the Linux hosts deploy from. Required when the range has Linux hosts."
  type        = string
  default     = ""
}

variable "windows_template" {
  description = "Name of a prepared Windows VM template the Windows hosts clone. Required when the range has Windows hosts."
  type        = string
  default     = ""
}

variable "ssh_public_key" {
  description = "Authorized key for the admin account, supplied at run time."
  type        = string
}

variable "operator_source_ranges" {
  description = "Where management access is accepted from. vSphere has no managed firewall, so this is advisory (host-level firewalling enforces it)."
  type        = list(string)
  default     = ["0.0.0.0/0"]
}

variable "lab_password" {
  description = "One shared lab password. Left empty, a strong one is generated at apply. Never in the export."
  type        = string
  default     = ""
  sensitive   = true
}
"""


def _tfvars():
    return """# Generated by redStackPRO. Fill these in before running terraform.
# Never commit this file with real values. See the project conventions.

vsphere_server   = ""
vsphere_user     = ""
vsphere_password = ""
datacenter       = "ha-datacenter"
datastore        = ""
resource_pool    = ""
esxi_host        = ""
vswitch          = "vSwitch0"
ssh_public_key   = ""

# Required for the hosts of that OS.
linux_ova_url    = ""
windows_template = ""
"""


# ---------------------------------------------------------------- addressing

def _segment_plan(plan):
    """A host that declares internal_ip on its overlay (e.g. a range locking
    to GOAD's canonical octets, see 0055) gets that exact address; every other
    host in the segment auto-assigns the next free one, skipping whatever the
    pinned hosts already claimed. Auto-assignment starts at .10 in segment
    order, matching the other on-prem backends."""
    seg_vlan, host_ip = {}, {}
    for i, seg in enumerate(plan.segments()):
        seg_vlan[seg["id"]] = 100 + i
    for seg in plan.segments():
        net = ipaddress.ip_network(seg["overlay"]["cidr"])
        here = sorted((h for h in plan.hosts()
                       if plan.primary_segment(h) == seg["id"]),
                      key=lambda n: n["id"])
        pinned = {h["id"]: h["overlay"]["internal_ip"] for h in here
                  if h.get("overlay", {}).get("internal_ip")}
        taken = set(pinned.values())
        auto = (str(net[i]) for i in range(10, net.num_addresses - 1)
                if str(net[i]) not in taken)
        for h in here:
            host_ip[h["id"]] = pinned.get(h["id"]) or next(auto)
    return seg_vlan, host_ip


def _prefixlen(cidr):
    return ipaddress.ip_network(cidr).prefixlen


def _gateway(cidr):
    return str(ipaddress.ip_network(cidr)[1])


# ---------------------------------------------------------------- root module

def _main(plan):
    is_range = plan.is_range()
    seg_vlan, host_ip = _segment_plan(plan)

    lines = [
        "# Generated by redStackPRO. Do not edit.",
        "# One module block per node. Inter module references resolve at apply",
        "# time on your machine, because redStackPRO never runs Terraform. See 0001.",
        "",
        "# Deploy-wide vSphere lookups, resolved once and passed to the modules.",
        'data "vsphere_datacenter" "dc" {',
        "  name = var.datacenter",
        "}",
        "",
        'data "vsphere_datastore" "ds" {',
        "  name          = var.datastore",
        "  datacenter_id = data.vsphere_datacenter.dc.id",
        "}",
        "",
        'data "vsphere_resource_pool" "pool" {',
        "  name          = var.resource_pool",
        "  datacenter_id = data.vsphere_datacenter.dc.id",
        "}",
        "",
        'data "vsphere_host" "host" {',
        "  name          = var.esxi_host",
        "  datacenter_id = data.vsphere_datacenter.dc.id",
        "}",
    ]

    if is_range:
        lines += [
            "",
            'resource "random_password" "lab" {',
            "  length           = 20",
            "  special          = true",
            '  override_special = "!@#-_=+"',
            '  min_special      = 1',
            "}",
            "",
            'resource "tls_private_key" "guacamole" {',
            '  algorithm = "ED25519"',
            "}",
            "",
            "locals {",
            "  lab_password = var.lab_password != \"\" ? var.lab_password : random_password.lab.result",
            "}",
        ]

    # A network is a routing domain with nothing to allocate on ESXi; segments
    # carry the VLANs on port groups.
    for node in plan.networks():
        lines += ["", 'module "%s" {' % plan.ref(node["id"])] + align([
            ("source", '"./modules/esxi/network"'),
            ("name", '"%s"' % plan.tag(node["id"])),
        ]) + ["}"]

    for node in plan.segments():
        lines += ["", 'module "%s" {' % plan.ref(node["id"])] + align([
            ("source", '"./modules/esxi/segment"'),
            ("name", '"%s"' % plan.tag(node["id"])),
            ("host_system_id", "data.vsphere_host.host.id"),
            ("datacenter_id", "data.vsphere_datacenter.dc.id"),
            ("vswitch", "var.vswitch"),
            ("vlan_id", str(seg_vlan[node["id"]])),
        ]) + ["}"]

    for node in plan.hosts():
        segment = plan.primary_segment(node)
        windows = is_windows(node)
        cores, memory = DEFAULT_MACHINE.get(node["kind"], (2, 4096))
        cidr = plan.ctx.overlay(segment, "cidr")
        pairs = [
            ("source", '"./modules/esxi/host"'),
            ("name", '"%s"' % plan.tag(node["id"])),
            ("node_id", '"%s"' % plan.tag(node["id"])),
            ("kind", '"%s"' % node["kind"]),
            ("resource_pool_id", "data.vsphere_resource_pool.pool.id"),
            ("datastore_id", "data.vsphere_datastore.ds.id"),
            ("datacenter_id", "data.vsphere_datacenter.dc.id"),
            ("network_id", "module.%s.network_id" % plan.ref(segment)),
            ("cores", str(cores)),
            ("memory", str(memory)),
            ("windows", "true" if windows else "false"),
            ("ip_address", '"%s"' % host_ip[node["id"]]),
            ("netmask", str(_prefixlen(cidr))),
            ("gateway", '"%s"' % _gateway(cidr)),
            ("ssh_public_key", "var.ssh_public_key"),
        ]
        if windows:
            pairs.append(("windows_template", "var.windows_template"))
        else:
            pairs.append(("linux_ova_url", "var.linux_ova_url"))
        disk = 120 if "exchange" in (node.get("overlay", {}).get("services") or []) else 40
        pairs.append(("disk_size", str(disk)))
        if is_range:
            pairs += [
                ("lab_password", "local.lab_password"),
                # The single platform identity (redop for ops, blueop for a
                # range): the Linux admin, the Windows local account, and the
                # Guacamole login are one account, not a separate "operator". See
                # P1.7 and naming.platform_account.
                ("operator_username", '"%s"' % plan.admin_account),
                ("guac_public_key", "tls_private_key.guacamole.public_key_openssh"),
                ("guac_private_key",
                 "tls_private_key.guacamole.private_key_openssh"
                 if node["kind"] == "jumpbox" else '""'),
            ]
        lines += ["", 'module "%s" {' % plan.ref(node["id"])] + align(pairs) + ["}"]

    if is_range:
        jumps = [n for n in plan.hosts() if n["kind"] == "jumpbox"]
        if jumps:
            jref = plan.ref(jumps[0]["id"])
            lines += [
                "",
                'output "guacamole" {',
                '  description = "The single pane of glass. Open the url and log in."',
                "  sensitive   = true",
                "  value = {",
                '    url      = "https://${module.%s.ip_address}/guacamole"' % jref,
                '    username = "%s"' % plan.admin_account,
                "    password = local.lab_password",
                "  }",
                "}",
            ]
        lines += [
            "",
            'output "lab_password" {',
            '  description = "Shared password for the operator account and the portal."',
            "  sensitive   = true",
            "  value       = local.lab_password",
            "}",
        ]

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------- firewall

def _firewall(plan):
    """vSphere has no managed per-VM firewall, so there is nothing to render.
    Segments isolate at layer 2 by VLAN (the port groups in the segment module);
    any east-west or ingress filtering is host-level or an appliance, which
    redStackPRO does not control or declare here. Michael's call, 2026-08-28."""
    return (
        "# Generated by redStackPRO. Do not edit.\n"
        "# vSphere exposes no managed per-VM firewall, so no rules are rendered.\n"
        "# Segments isolate at layer 2 by VLAN (see the port groups in main.tf).\n"
        "# Host-level or appliance firewalling is the operator's, by design.\n")
