"""The Proxmox backend (bpg/proxmox).

On-prem per 0003. A Proxmox host has no allocated public address and no managed
private DNS, and outbound routing is a precondition of the host network rather
than a resource (see the registry). So a "network" is a routing domain realised
as a VLAN, a "segment" is a VLAN carrying a CIDR, and a peers edge has nothing to
compile to. Proxmox has no cloud DHCP either, so each host takes a static address
allocated from its segment here.

Linux hosts come up from a cloud image with cloud-init (the strong path). Windows
hosts boot an operator-supplied ISO with the VirtIO drivers and an autounattend
answer file, then are provisioned over WinRM the same as the other backends. The
firewall is the Proxmox VM firewall, driven by the same edges. See 0015.
"""

import ipaddress

from .plan import GenerationError, align  # noqa: F401  GenerationError re-exported

# Cloud images for the Linux builds, downloaded to the ISO datastore at apply.
# Windows has no cloud image, so a Windows host takes an operator-supplied ISO
# (proxmox_windows_iso_url) and installs unattended.
# Debian 13 (trixie) by default; see the note in gcp.py for the Python floor
# that forced it. bookworm stays reachable for a topology that names debian_12.
LINUX_IMAGES = {
    "debian": "https://cloud.debian.org/images/cloud/trixie/latest/debian-13-genericcloud-amd64.qcow2",
    "debian_13": "https://cloud.debian.org/images/cloud/trixie/latest/debian-13-genericcloud-amd64.qcow2",
    "debian_12": "https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-genericcloud-amd64.qcow2",
    "ubuntu_2204": "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img",
    "ubuntu_2004": "https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img",
    # Trixie rather than bookworm: Kali tracks Debian testing, so the newer base
    # is the closer stand-in, and it is the same interpreter the toolchain is
    # resolved against everywhere else.
    "kali": "https://cloud.debian.org/images/cloud/trixie/latest/debian-13-genericcloud-amd64.qcow2",
}

# Windows builds all boot the same operator-supplied ISO; the build only labels
# the guest. GCP has no client image either, and here the ISO is the operator's,
# so a workstation and a server differ only in the answer file's edition.
WINDOWS_BUILDS = {
    "windows_server_2016", "windows_server_2019", "windows_server_2022",
    "windows_10", "windows_11", "windows",
}

# Machine sizing per kind, in (cores, memory_mb). Overridable in tfvars.
DEFAULT_MACHINE = {
    "collector": (2, 4096),
    "operator": (2, 4096),
    "dc": (2, 4096),
    "srv": (2, 4096),
    "wks": (2, 2048),
    "siem": (4, 8192),
}


def is_windows(node):
    return node.get("overlay", {}).get("os", "") in WINDOWS_BUILDS \
        or (node["kind"] in ("dc", "srv", "wks")
            and not node.get("overlay", {}).get("os", "").startswith(("debian", "ubuntu", "linux")))


def image_url_for(node):
    overlay = node.get("overlay", {})
    if node["kind"] == "operator":
        return LINUX_IMAGES.get(overlay.get("os", "debian"), LINUX_IMAGES["debian"])
    return LINUX_IMAGES.get(overlay.get("os"), LINUX_IMAGES["debian"])


def files(plan):
    return {
        "terraform/versions.tf": _versions(),
        "terraform/variables.tf": _variables(),
        "terraform/terraform.tfvars": _tfvars(),
        "terraform/main.tf": _main(plan),
        "terraform/firewall.tf": _firewall(plan),
    }


# ---------------------------------------------------------------- static parts

def _versions():
    return """# Generated by redStackPRO. Do not edit.
# redStackPRO does not run Terraform and does not bundle the binary. See 0001, 0002.

terraform {
  required_version = ">= 1.5"

  required_providers {
    proxmox = {
      source  = "bpg/proxmox"
      version = "~> 0.66"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.0"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0"
    }
  }
}

provider "proxmox" {
  endpoint  = var.proxmox_endpoint
  api_token = var.proxmox_api_token
  insecure  = var.proxmox_insecure
  ssh {
    agent = true
  }
}
"""


def _variables():
    return """# Generated by redStackPRO. Do not edit.
# Values live in terraform.tfvars. Credentials and key material never do.

variable "proxmox_endpoint" {
  description = "Proxmox API endpoint, e.g. https://pve.example.lan:8006/"
  type        = string
}

variable "proxmox_api_token" {
  description = "Proxmox API token, e.g. root@pam!redstackpro=<uuid>. Supplied at run time."
  type        = string
  sensitive   = true
}

variable "proxmox_insecure" {
  description = "Skip TLS verification of the Proxmox endpoint (self-signed labs)."
  type        = bool
  default     = true
}

variable "proxmox_node" {
  description = "The Proxmox node that hosts the range."
  type        = string
  default     = "pve"
}

variable "proxmox_datastore" {
  description = "Datastore for VM disks, e.g. local-lvm."
  type        = string
  default     = "local-lvm"
}

variable "proxmox_iso_datastore" {
  description = "Datastore that holds downloaded images and ISOs, e.g. local."
  type        = string
  default     = "local"
}

variable "proxmox_bridge" {
  description = "The Linux bridge every segment VLAN rides on, e.g. vmbr0."
  type        = string
  default     = "vmbr0"
}

variable "proxmox_windows_iso_url" {
  description = "URL of the Windows installation ISO. Required only when the range has Windows hosts."
  type        = string
  default     = ""
}

variable "ssh_public_key" {
  description = "Authorized key for the admin account, supplied at run time."
  type        = string
}

variable "operator_source_ranges" {
  description = "Where management access is accepted from. Narrow this."
  type        = list(string)
  default     = ["0.0.0.0/0"]
}

variable "lab_password" {
  description = "One shared lab password for the admin account, the Windows operator, and the Guacamole login. Left empty, a strong one is generated at apply. Never in the export."
  type        = string
  default     = ""
  sensitive   = true
}
"""


def _tfvars():
    return """# Generated by redStackPRO. Fill these in before running terraform.
# Never commit this file with real values. See the project conventions.

proxmox_endpoint  = "https://pve.example.lan:8006/"
proxmox_api_token = ""
proxmox_node      = "pve"
proxmox_datastore = "local-lvm"
proxmox_bridge    = "vmbr0"
ssh_public_key    = ""

# Required when the range has Windows hosts.
proxmox_windows_iso_url = ""

# Narrow this to the addresses operators connect from.
operator_source_ranges = ["0.0.0.0/0"]
"""


# ---------------------------------------------------------------- addressing

def _segment_plan(plan):
    """Assign each segment a VLAN id and each host a static address in it, since
    Proxmox has no cloud DHCP. VLANs start at 100 in topology order. A host that
    declares internal_ip on its overlay (e.g. a range locking to GOAD's
    canonical octets, see 0055) gets that exact address; every other host in
    the segment auto-assigns the next free one, skipping whatever the pinned
    hosts already claimed. Auto-assignment starts at .10 in segment order,
    leaving .1 for the gateway the host network provides."""
    seg_vlan, host_ip = {}, {}
    for i, seg in enumerate(plan.segments()):
        seg_vlan[seg["id"]] = 100 + i
    for seg in plan.segments():
        net = ipaddress.ip_network(seg["overlay"]["cidr"])
        here = sorted((h for h in plan.hosts()
                       if plan.primary_segment(h) == seg["id"]),
                      key=lambda n: n["id"])
        pinned = {h["id"]: h["overlay"]["internal_ip"] for h in here
                  if h.get("overlay", {}).get("internal_ip")}
        taken = set(pinned.values())
        auto = (str(net[i]) for i in range(10, net.num_addresses - 1)
                if str(net[i]) not in taken)
        for h in here:
            addr = pinned.get(h["id"]) or next(auto)
            host_ip[h["id"]] = "%s/%d" % (addr, net.prefixlen)
    return seg_vlan, host_ip


def _gateway(cidr):
    return str(ipaddress.ip_network(cidr)[1])


# ---------------------------------------------------------------- root module

def _main(plan):
    is_range = plan.is_range()
    seg_vlan, host_ip = _segment_plan(plan)

    lines = [
        "# Generated by redStackPRO. Do not edit.",
        "# One module block per node. Inter module references resolve at apply",
        "# time on your machine, because redStackPRO never runs Terraform. See 0001.",
    ]

    if is_range:
        lines += [
            "",
            "# One shared lab password, generated at apply unless the operator set one.",
            'resource "random_password" "lab" {',
            "  length           = 20",
            "  special          = true",
            '  override_special = "!@#-_=+"',
            "}",
            "",
            "# The jumpbox reaches every box for the Guacamole tiles with this key.",
            'resource "tls_private_key" "guacamole" {',
            '  algorithm = "ED25519"',
            "}",
            "",
            "locals {",
            "  lab_password = var.lab_password != \"\" ? var.lab_password : random_password.lab.result",
            "}",
        ]

    # A network is a routing domain with nothing to allocate on Proxmox; segments
    # carry the VLANs. It stays as a module for symmetry and so a future SDN
    # backend has a seam. See the registry.
    for node in plan.networks():
        lines += ["", 'module "%s" {' % plan.ref(node["id"])] + align([
            ("source", '"./modules/proxmox/network"'),
            ("name", '"%s"' % plan.tag(node["id"])),
        ]) + ["}"]

    for node in plan.segments():
        lines += ["", 'module "%s" {' % plan.ref(node["id"])] + align([
            ("source", '"./modules/proxmox/segment"'),
            ("name", '"%s"' % plan.tag(node["id"])),
            ("cidr", '"%s"' % node["overlay"]["cidr"]),
            ("vlan_id", str(seg_vlan[node["id"]])),
        ]) + ["}"]

    for node in plan.hosts():
        segment = plan.primary_segment(node)
        windows = is_windows(node)
        cores, memory = DEFAULT_MACHINE.get(node["kind"], (2, 4096))
        pairs = [
            ("source", '"./modules/proxmox/host"'),
            ("name", '"%s"' % plan.tag(node["id"])),
            ("node_id", '"%s"' % plan.tag(node["id"])),
            ("kind", '"%s"' % node["kind"]),
            ("proxmox_node", "var.proxmox_node"),
            ("datastore", "var.proxmox_datastore"),
            ("iso_datastore", "var.proxmox_iso_datastore"),
            ("bridge", "var.proxmox_bridge"),
            ("vlan_id", "module.%s.vlan_id" % plan.ref(segment)),
            ("ip_address", '"%s"' % host_ip[node["id"]]),
            ("gateway", '"%s"' % _gateway(plan.ctx.overlay(segment, "cidr"))),
            ("cores", str(cores)),
            ("memory", str(memory)),
            ("windows", "true" if windows else "false"),
            ("ssh_public_key", "var.ssh_public_key"),
            # The single platform account (redop for ops, blueop for a range). See P1.7.
            ("admin_username", '"%s"' % plan.admin_account),
        ]
        if windows:
            pairs.append(("windows_iso_url", "var.proxmox_windows_iso_url"))
        else:
            pairs.append(("image_url", '"%s"' % image_url_for(node)))
        # Exchange needs room for a 6 GB ISO plus a large install.
        disk = 120 if "exchange" in (node.get("overlay", {}).get("services") or []) else 40
        pairs.append(("disk_size", str(disk)))
        if is_range:
            pairs += [
                ("enable_winrm", "true" if windows else "false"),
                ("lab_password", "local.lab_password"),
                # Same single platform identity as the Linux admin (redop for ops,
                # blueop for a range), not a separate "operator". See P1.7 and
                # naming.platform_account.
                ("operator_username", '"%s"' % plan.admin_account),
                ("guac_public_key", "tls_private_key.guacamole.public_key_openssh"),
                ("guac_private_key",
                 "tls_private_key.guacamole.private_key_openssh"
                 if node["kind"] == "jumpbox" else '""'),
            ]
        lines += ["", 'module "%s" {' % plan.ref(node["id"])] + align(pairs) + ["}"]

    if is_range:
        jumps = [n for n in plan.hosts() if n["kind"] == "jumpbox"]
        if jumps:
            jref = plan.ref(jumps[0]["id"])
            lines += [
                "",
                'output "guacamole" {',
                '  description = "The single pane of glass. Open the url and log in."',
                "  sensitive   = true",
                "  value = {",
                '    url      = "https://${module.%s.ip_address}/guacamole"' % jref,
                '    username = "%s"' % plan.admin_account,
                "    password = local.lab_password",
                "  }",
                "}",
            ]
        lines += [
            "",
            'output "lab_password" {',
            '  description = "Shared password for the admin account, the Windows operator, and the portal."',
            "  sensitive   = true",
            "  value       = local.lab_password",
            "}",
        ]

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------- firewall

def _firewall(plan):
    """The Proxmox VM firewall, one rules block per host, driven by the same
    edges as the cloud backends. A peers edge has nothing to compile to on
    Proxmox (the registry marks peering unsupported), so only the intra-VLAN and
    management paths appear here."""
    ctx = plan.ctx

    # One firewall_rules resource per host: Proxmox rejects two blocks for the
    # same VM, so every rule a host receives is accumulated here and emitted once.
    rules_by_host = {}

    def add(host_id, rule):
        rules_by_host.setdefault(host_id, []).append(rule)

    def seg_cidr(host_id):
        return ctx.overlay(plan.primary_segment(ctx.nodes[host_id]), "cidr")

    # manages: operator to the jumpbox (22, and 443 for the portal on a range),
    # then the jumpbox to each host it manages on that host's management port.
    for edge in ctx.by_role.get("manages", []):
        jump = edge["source"]
        add(jump, _fw_rule("in", "ACCEPT", "tcp", 22,
                           source="var.operator_source_ranges",
                           comment="operator ssh"))
        # Guacamole runs on the jumpbox in every mode (range and offense), so open
        # 443 to the portal regardless of range/ops.
        add(jump, _fw_rule("in", "ACCEPT", "tcp", 443,
                           source="var.operator_source_ranges",
                           comment="operator guacamole"))
        # The jumpbox is the range foothold: it must receive traffic range hosts
        # initiate back to it (coerced/relayed NTLM to an operator listener, a
        # pivoted callback). Internal (segment) surface only. Mirrors the AD
        # all-from-segment rule below. See part-04 and gcp.py's foothold rule.
        add(jump, _fw_rule("in", "ACCEPT", "all", None,
                           source_literal=[seg_cidr(jump)],
                           comment="range foothold accepts callbacks from its segment"))
        for host in sorted(plan.hosts(), key=lambda h: h["id"]):
            if host["id"] == jump or ctx.manager_of(host["id"]) != jump:
                continue
            add(host["id"], _fw_rule("in", "ACCEPT", "tcp",
                                     plan.management_port(host),
                                     source_literal=[seg_cidr(jump)],
                                     comment="%s manages this host" % ctx.name(jump)))
            # guacd on the jumpbox reaches a Windows box's RDP tile on 3389.
            if plan.is_windows(host):
                add(host["id"], _fw_rule("in", "ACCEPT", "tcp", 3389,
                                         source_literal=[seg_cidr(jump)],
                                         comment="%s reaches this host's RDP tile"
                                                 % ctx.name(jump)))

    # joins: every AD host accepts all traffic from its own segment, the way a
    # member reaches its DC to join and DCs replicate. See the AWS backend.
    for host in plan.intra_segment_hosts():
        add(host["id"], _fw_rule("in", "ACCEPT", "all", None,
                                 source_literal=[seg_cidr(host["id"])],
                                 comment="intra-domain traffic from the segment"))

    lines = [
        "# Generated by redStackPRO. Do not edit.",
        "# Every rule below exists because of an edge in the topology. The Proxmox",
        "# firewall is per VM, so a host's rules live in one block keyed on its id.",
    ]
    for host_id in sorted(rules_by_host):
        lines += _fw_block(plan, host_id, rules_by_host[host_id])

    return "\n".join(lines) + "\n"


def _fw_rule(direction, action, proto, port, source=None, source_literal=None,
             comment=None):
    return {
        "direction": direction, "action": action, "proto": proto,
        "port": port, "source": source, "source_literal": source_literal,
        "comment": comment,
    }


def _fw_block(plan, host_id, rules):
    ref = plan.ref(host_id)
    lines = [
        "",
        'resource "proxmox_virtual_environment_firewall_rules" "%s" {' % ref,
        "  node_name = var.proxmox_node",
        "  vm_id     = module.%s.vm_id" % ref,
        "",
    ]
    for r in rules:
        lines.append("  rule {")
        body = [
            ("type", '"%s"' % ("in" if r["direction"] == "in" else "out")),
            ("action", '"%s"' % r["action"]),
        ]
        if r["proto"] and r["proto"] != "all":
            body.append(("proto", '"%s"' % r["proto"]))
        if r["port"]:
            body.append(("dport", '"%s"' % r["port"]))
        # A rule may take its source from a variable list or a literal CIDR list.
        if r["source"]:
            body.append(("source", "join(\",\", %s)" % r["source"]))
        elif r["source_literal"]:
            body.append(("source", '"%s"' % ",".join(r["source_literal"])))
        if r["comment"]:
            body.append(("comment", '"%s"' % r["comment"]))
        lines += align(body, indent="    ") + ["  }"]
    lines.append("}")
    return lines
